### ISSUE TITLE
Feature request: movement for maps in side view

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#118]
To be able to make maps in side view (like in Link's Awakening), we need an additional movement type for the hero with gravity.

**Comment by christopho** [comment]
See also wrightmat script: http://forum.solarus-games.org/index.php/topic,297.0.html

**Comment by wrightmat** [comment]
It's my opinion that we should avoid hard-coding features into the engine if they can be created via scripting, so I almost think this issue should be closed. What do you think Christopho?

**Comment by Nate-Devv** [comment]
I second @wrightmat. Perhaps add the script to the sample quest?

**Comment by christopho** [comment]
I am not sure yet, I will need to make some tests.

**Comment by christopho** [comment]
Ok, closing the issue. It can clearly be scripted, so no need to hardcode the feature.
