### ISSUE TITLE
Editor: maven recompiles everything all the time

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#430]
$ cd tools
$ ./compile

Even if there is no change, even when doing ./compile twice maven always says:
Changes detected - recompiling the module!

and everything is recompiled.

**Comment by christopho** [comment]
Fixed in v1.4.

And the fix consists in rewriting the editor in C++ :)

**Comment by sam101** [comment]
I think that's one of the best fix ever :)

**Comment by christopho** [comment]
Definitely :)
