### ISSUE TITLE
Add more show/hide options to the editor

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#476]
In the map editor, it would be helpful to have a show/hide toggle for obstacles (for the hero) vs. non-obstacles, especially with tiles (like we have for layers and such). Normally you can't tell which tiles are obstacles without going to the tileset editor and looking at each tile.

Also changing the way the editor toggles these show/hide options could make room for more. I'd recommend adding a "View" menu with check/uncheck options for each of the types we have now and may add in the future. Then they can be taken off the toolbar entirely or limited to a few of the most popular ones (but more would be available to the user).

**Comment by christopho** [comment]
Moved this issue to the quest editor repository: https://github.com/christopho/solarus-quest-editor/issues/6
