### ISSUE TITLE
Permettre de changer la taille de la caméra.

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus#531]
Dans tout les zelda 2D (excepté alttp), le hud prend toute la partie supérieure de l'écran.

Il faudrait pouvoir avoir une caméra plus petite que l'écran et pouvoir la positionner où on veut sur l'écran.

**Comment by christopho** [comment]
It should be doable if the camera is an entity. With camera:set_size() and camera:set_origin() you will be able to setup the camera like you want.

**Comment by Diarandor** [comment]
I point out that the camera cannot be centered to a point in a side or coin of the map if the map is too small. So, currently, to make a quake effect, it is necessary to have a map big enough in width/height, to move the camera (at least I had that problem). 

Fortunately, this problem should dissapear when you implement the camera entity.

**Comment by christopho** [comment]
Yes, by using movement:set_ignore_obstacles(true) on the camera. The camera will then ignore separators and map limits. The background around the map will be the tileset's background color.

**Comment by Diarandor** [comment]
Ok, I didn't know it was already possible. Thanks!

**Comment by christopho** [comment]
Just to be clear, it is not possible yet, but we should add the feature in Solarus 1.5.

**Comment by christopho** [comment]
Done!
