### ISSUE TITLE
Pickable object may break if thrown when changing direction

### ISSUE THREAD

**Issue by Morwenn** [christopho/solarus#602]
In the sample quest, I am facing right while holding a rock. If I press at the same time the keys to throw the rock and go up, the rock sometimes breaks without having been thrown. I haven't tried to reproduce this bug for the other directions.

**Comment by christopho** [comment]
I can't reproduce the bug. Are you sure that there is no obstacle to the north when trying to throw the rock there?
Feel free to reopen with more details if you still have the problem.
