### ISSUE TITLE
Editor: find and replace in the code editor

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#640]
Implement a find and replace feature in the script editor.

**Comment by Bapt1** [comment]
Hello criztopho (I muzt appologize for zome technical probelmz with my keyboard....)
But zince I'v updated My zolaruz I have a lot of bug.. Firzt on my firzt file the arrow key have cezzed to work :+1: Error: In on_started: [string "items/arrow.lua"]:15: Item 'bow' is not saved
Error: In on_started: [string "items/quiver.lua"]:26: Item 'bow' has no amount
Error: In on_started: [string "hud/item_icon.lua"]:53: Item 'feather' is not saved

After thiz the menu wich iz all fuckep up.... All the inventary dizapear and the control on the left top corner alzo dizzapear....

Error: In on_started: [string "menus/pause_inventory.lua"]:50: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_finished: [string "menus/pause_inventory.lua"]:91: attempt to index field 'item_icon_1' (a nil value)
Error: In on_started: [string "menus/pause_inventory.lua"]:50: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_finished: [string "menus/pause_inventory.lua"]:91: attempt to index field 'item_icon_1' (a nil value)
Error: In on_started: [string "menus/pause_inventory.lua"]:50: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved
Error: In on_draw: [string "menus/pause_inventory.lua"]:213: Item 'feather' is not saved


P.Z : I wizh than I could offer you an opportunity to have a new tezter on your team...  If you accept...

**Comment by christopho** [comment]
Hi,
Your problem is not related to this bug, please file a new bug if you want to report something.

**Comment by Bapt1** [comment]
J'avais pas le droit... Désolé.... J'étais en essais... Je n'avais pas validé le mail de confirmation....

Avec la nouvelle la poste.net ne peux plus faire copier et coller dans le corps texte génial comme ajout? Hein? Comme ça quand tu veux partager une vidéo avec un pote, bah t'as tout à recopier à la main !!!!! Ou bien tu passe en format Htlm et t'as plus gérer la police ( ajouter des simley, mettre en gras, changer la couleur la taille centrer et j'en passe) chose qui était possible avant en même temps que de pouvoir coller !!! 

----- Mail original -----
De: "Christopho" <notifications@github.com>
À: "christopho/solarus" <solarus@noreply.github.com>
Cc: "Bapt1" <b.cellier962@laposte.net>
Envoyé: Jeudi 15 Janvier 2015 10:54:24
Objet: Re: [solarus] Editor: find and replace in the code editor (#640)

Hi,
Your problem is not related to this bug, please file a new bug if you want to report something.

---

**Comment by christopho** [comment]
Moved this issue to the quest editor repository: https://github.com/christopho/solarus-quest-editor/issues/3
