### ISSUE TITLE
Dynamic tiles and other ground types

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#644]
Create a tile (or a custom entity in fact) and assign a movement. It won't traverse other ground types such as deep water or holes - even with set_can_traverse_ground("deep_water", true) or set_can_traverse_ground("hole", true).

**Comment by wrightmat** [comment]
This may have also been fixed by fixing #668. I'll gladly test it when the next stable version is released.

**Comment by christopho** [comment]
Indeed, this is the same bug.
