### ISSUE TITLE
Request : more game commands

### ISSUE THREAD

**Issue by fosamax** [christopho/solarus#652]
Could it be possible to allow more built-in game action so that it better fits more gaming style.
I guess those game command could remain unactive in the current implentation of zelda solarus.

Here's what I can think :
"action": Contextual action such as talking, swimming, throwing, etc.
"attack_1": Main attack (using the sword).
"attack_2": Secondary attack (using custom entity ?)
"backstab": Stealth attack
"dodge": Prevent damage
"pause": Pausing or unpausing the game. (real freeze of the game)
"menu": Access or escape last selected menu (may replace current pause)
"map": Direct access to the map
"inventory": Direct access to the inventory
"status": Direct access to the quest's status
"options": Direct access to option menu
"item_1": Using the equipment item placed in slot 1 (see game:get_item_assigned())
"item_2": Using the equipment item placed in slot 2 (see game:get_item_assigned())
"right": Moving to the right.
"left": Moving to the left.
"up": Moving to the top.
"down": Moving to the bottom.
"next": Perform next action
"previous": Perform previous action

"custom1": Perform custom action 1 (scripted)
"custom2": Perform custom action 2 (scripted)
"custom3": Perform custom action 3 (scripted)
"custom4": Perform custom action 4 (scripted)

next and previous could have a different behaviour whether you're inside or outside the menu.

Currently I would like to use the following game command to improve playability on mobile devices :
- menu : access last selected menu (mapped on start button for example)
- map : direct access to the map (mapped on select button for example)
- previous and next : switch between map/inventory/status/option when in menu

I understand adding more built-in game action would require that option menu should be made scrollable to fit the added action (even if all are not made available)

**Comment by christopho** [comment]
Actually you can implement game:on_key_pressed() to react to any physical key and do custom actions like all the ones you mention :) So there is no need to more built-in things.

**Comment by fosamax** [comment]
Thanks for pointing this !
