### ISSUE TITLE
map:set_world()

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#656]
Like other get/set pairs, it would be helpful to be able to dynamically set the world of a map. map:set_floor() may also be a logical addition.

**Comment by christopho** [comment]
But it is supposed to be a constant property (same for the floor). Do you have a use case?

**Comment by wrightmat** [comment]
Yes. I have a couple outdoor maps that are actually part of a dungeon (at least sections of the map are) so in order for this to work, those maps have to be part of the "dungeon_2" world. This causes problems with other scripts that need the maps to be part of the "outside_world" world, so my solution would be to flex the world on map_started depending on what destination the hero's coming from. If coming from the inside part of the dungeon, make the map part of the "dungeon_2" world, otherwise it will remain as "outside_world". Is there another solution to this you could think of?

**Comment by christopho** [comment]
Ok, this is useful indeed!

**Comment by wrightmat** [comment]
I don't have a use case from my game for set_floor, I was originally just thinking for consistency. I could think of one from an existing Zelda game though, once again from a dungeon. In Eagle's Tower from Link's Awakening, you destroy pillars in order to destroy levels of the tower. This would cause the existing floors to change. If someone wanted to implement this in Solarus, it would be difficult without map:set_floor()
