### ISSUE TITLE
Problem when scripting platforms or wind (possible bug)

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#660]
Hi, I have the following problem (it is quite a bit hard to explain), and it could be a bug.
I made scripts for platforms and wind that move the hero changing his coordinates.

-For the platforms, I change the coordinates of the hero using the event on_position_changed of the platform (the platform is moved with a movement of the engine). The problem appears when the hero is carrying an object (a pot for example) and the camera is moving following the hero at the same time (to test this the map must be big). Sometimes, the sprite of item that is being carried is showed like vibrating (from left to right to left, etc, if the direction of the movement is horizontal). This only happens sometimes (and the camera must be moving to make this happen). Maybe the sprite of the carried item is not refreshed in the correct time, or something like that... (I tested a script of wind, using the same method and the same happens, obviously.)

-I made another script of wind using a different method: the position of the hero is changed using a timer with a loop. In this case, when the camera is moving after the hero, the carried item is moved smoothly, but the sprite of the hero appears like vibrating (the same problem as above but in the sprite of the hero in this case). The same happens when I apply the movement to other custom entities that are not the hero (I emphasize that the camera must be moving to make this happen).

Obviously, my aim is to make the movement smooth for the hero, carried items, and other entities where I apply the movement, when the camera is moving, if this is possible. Do you have the same problem? (Maybe I am doing something wrong) Could this be a bug of the engine? I would like to find a solution for this... or I will be forced to use small maps when I use this kind of entities.

Thanks in advance for your help!

**Comment by christopho** [comment]
I will try to solve this for 1.4 if the fix is not too risky, because I understand that it is very annoying and I don't see any workaround except making smaller maps (or using separators).

**Comment by christopho** [comment]
I think I fixed it, but I am not sure I was exactly reproducing the problem. Please confirm that the issue is solved. Thanks

**Comment by Diarandor** [comment]
Ok, I will test it when solarus 1.4 is released (I don't know how to compile solarus from the source code, sorry).

**Comment by Diarandor** [comment]
Yes, I confirm that the problem is fixed now. Thanks!
