### ISSUE TITLE
Surfaces and text surfaces cannot be displayed in map coordinates

### ISSUE THREAD

**Issue by thebread27** [christopho/solarus#661]
It doesn't appear to be possible to display surfaces (also text surfaces) in the manner of tiles (sidescrolling, walkable) yet.

**Comment by christopho** [comment]
Sprites can be displayed as entities with map:draw_sprite(), but surfaces and text surfaces cannot.
See also the discussion of http://forum.solarus-games.org/index.php?topic=221.msg675;topicseen#new
