### ISSUE TITLE
chest:set_treasure

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#664]
It would be helpful to conditionally set the contents of a treasure chest. For example, a script checks at runtime whether the hero already has a certain treasure, or has a certain amount of a treasure, and adjusts the contents accordingly.

**Comment by christopho** [comment]
Agreed.
In the meantime, a way to obtain the same result is to make the chest empty, and to give something on-deman, by calling hero:start_treasure() from chest:on_empty().

**Comment by wrightmat** [comment]
It occurred to me that I could just destroy the chest and create a new one in its place.

**Comment by christopho** [comment]
See also #483. Both issues should be treated in the same version.
