### ISSUE TITLE
Editor feature request: glue/unglue entities in the editor.

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#665]
Hi! I thought that it would be nice to have some button to glue several entities (or at least tiles) of the map editor; this option should be either a button above in the editor or an option for the right click context menu when a group of entities is selected at the same time (or maybe in both places). 

This is useful, for instance, if you create a house on the map editor and later you decide to move it to another part of the map, you would not need to move all the sprites/entities of the house one by one. In the context menu that appears with right click on a group of glued entities, there should be an option to unglue all the entities glued in that group. It should also be possible to glue two groups of glued entities in a new one, and to copy-paste groups of glued entities.

I suggest to add 2 buttons in the editor, above. One to glue selected entities. The other button would be a "check box" to enable/disable the "glue feature" temporarily (this would allow to move an entity with respect of the entities of the same glued group without ungluing the group). In other words, when the "glue feature" is enabled, if you click on an entity of the grup, all the entities of its group would be selected at the same time; if the feature is disabled, only the entity in which you click would be selected, but not the other entities of its group.

Thanks a lot!!!

**Comment by christopho** [comment]
This is probably a good idea.

**Comment by Morwenn** [comment]
Where is the « like » button?

**Comment by christopho** [comment]
This issue was moved to christopho/solarus-quest-editor#126
