### ISSUE TITLE
Amélioration de `require` dans les scripts Lua

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus#666]
__Solarus__ remplace la fonction standard `require` de Lua dans les scripts de quête mais le comportement de cette nouvelle fonction ne repoduit pas complètement celui de la fonction standard.

Dans certains cas pouvoir utiliser un chemin relatif au fichier qui fait le `require` pourraît être pratique. Notamment si l'on souhaite écrire une *lib* pour __Solarus__, on aimerait pouvoir utiliser des chemins relatifs entre les fichiers interne de cette *lib* de manière à ce que peut importe dans quel dossier les utilisateurs le copie dans leur quête elle fonctionne sans problèmes.

Pour le moment dans ce cas de figure si des fichiers nécéssitent `require` dans une *lib* il faut imposer le dossier dans lequel la copier chez les utilisateurs. Le chemin doit être relatif au dossier `data/`.

On pourrait aussi pouvoir utiliser les notations `.` et `..`, sans pouvoir passer hors du dossier `data/` bien sur.

Une dernière idée pourrait aussi être de tester (un peu comme le fait la fonction standard) si le chemin du `require` correspond a un dossier qui contiendait un fichier `init.lua` (ou pourquoi pas `main.lua`). 

Bref voici quelques exemples de `require` qui ne fonctionnent pas pour l'instant :
```lua
require("fichier_local") -- fait depuis un autre dossier de que le `data/` 
require("./fichier_local")
require("../gui/widget")
require("libs/super_lib") -- super_lib étant un dossier contenant un fichier `init.lua`
require("libs/super_lib/")
```

**Comment by christopho** [comment]
Normalement, c'est le require() standard qui est utilisé. Solarus ne fait qu'ajouter le répertoire data à la liste des chemins testés. Ça ne fonctionne pas ?

**Comment by Maxs1789** [comment]
Les exemples que j'ai donné ne fonctionnent pas. 

On voit bien dans l'erreur donnée que Lua cherche aussi mais il n'a apparement pas un bon chemin qui lui est donné.

Après y a toujours le cas des archives de quête ou la Lua ne pourra pas trouvé tout seul. Enfin si je comprend bien comment ça marche.

**Comment by christopho** [comment]
Justement, Solarus ajoute un mécanisme pour rechercher les fichiers dans data/ comme dans data.solarus. (Ceci en plus des chemins de recherche habituels de Lua).

**Comment by Maxs1789** [comment]
Voici un exemple complet pour que tu puisse reproduire le bug.

##### Dossier `data/`
- `project_db.dat` vide
- `quest.dat` qui contient :
```lua
quest{
  solarus_version = "1.3",
  title_bar = "problème de require"
}
```
- `main.lua` qui contient :
```lua
require("test/fichier_a")
```
##### Dossier `data/test/`
- `fichier_a.lua` qui contient :
```lua
require("fichier_b")
-- Ces deux autres exemples ne fonctionnent pas non plus :
--   require("fichier_b.lua")
--   require("./fichier_b")
--
-- Mais celui ci fonctionne correctement :
--   require("test/fichier_b")
```
- `fichier_b.lua` qui contient :
```lua
print("fichier b chargé") -- n'est pas affiché car le fichier n'est pas correctement chargé
```
---
Voici l'erreur que j'obtient :
```
Error: In main: [string "test/fichier_a.lua"]:1: module 'fichier_b' not found:
	no field package.preload['fichier_b']
	no quest file 'fichier_b.lua' in 'data/', 'data.solarus' or 'data.solarus.zip'
	no file './fichier_b.lua'
	no file '/usr/share/luajit-2.0.3/fichier_b.lua'
	no file '/usr/local/share/lua/5.1/fichier_b.lua'
	no file '/usr/local/share/lua/5.1/fichier_b/init.lua'
	no file '/usr/share/lua/5.1/fichier_b.lua'
	no file '/usr/share/lua/5.1/fichier_b/init.lua'
	no file './fichier_b.so'
	no file '/usr/local/lib/lua/5.1/fichier_b.so'
	no file '/usr/lib/lua/5.1/fichier_b.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by Maxs1789** [comment]
J'ai fais quelques test avec Lua directement et en fait ce comportement semble à peu près normal.
Depuis le dossier `data/` je tappe la commande `lua main.lua` et j'obtient le même genre d'erreur.
Ceci dit j'ai des réactions un peu étrange, si je met le code qui suit dans le `fichier_a.lua` :
```lua
-- Ces exemples ne fonctionnent pas :
require("fichier_b")
require("./fichier_b")
require("fichier_b.lua")

-- Ceux ci fonctionnent bien :
require("test/fichier_b")
require("../test/fichier_b")      -- ne fonctionne pas avec solarus
require("../test/fichier_b.lua")  -- ne fonctionne pas avec solarus
```
Du coup je ne sais pas trop ce qui est le mieux à faire, même si la syntaxe `.` et `..` pourraît être utile elle n'est pas indispensable.
Le fait de ne pas gérer tous ces cas signifierai donc que pour une *lib* écrite pour __Solarus__ on devrait imposer le dossier dans lequel la copier. Ce n'est pas si mal après tout, mais il faudrait dans ce cas être un peu plus clair dans la doc au sujet du `require`. C'est à dire : tous les chemins passés à `require` doivent être relatif au dossier `data/` de la quête ( c'est comme ça pour l'instant en tout cas).

**Comment by Maxs1789** [comment]
Juste une idée comme ça du coup, on pourrait imaginer que __Solarus__ cherche dans un dossier de *lib* prévu pour ça (un peu comme le fait Lua) dans un dossier `data/libs/` par exemple. Il ferait donc :
- chercher le fichier normalement (dans `data/`)
- si non trouvé, chercher le fichier dans `data/libs/nom_du_fichier.lua`
- si non trouvé, chercher le fichier `data/libs/nom_du_fichier/init.lua`

Ensuite dans un futur lointain, on pourraît imaginer que l'éditeur gère les *libs* à l'aide d'un fichier descriptif nommé `lib.dat` (au lieu de `quest.dat`) qui ressemblerait à ça :
```lua
lib{
  name = "my-lib",
  version = "0.1",
  solarus_version = "1.3",
  scripts = { 
    "fichier_a.lua",
    "fichier_b.lua"
  }
  -- sprites = { ... } ?
  -- ennemies = ...
}
```
Le solarus-logo, les systèmes de dialogue, des ennemis génériques pourraît être proposés comme des *libs*. 
On pourraît aller loin dans l'idée et proposer une gestion de dépendances entre les *libs* avec tout un système de ressources interne aux *libs*, un système de mise à jour par l'éditeur (utilisant github par exemple), etc ...
Bien sur tout ça n'est qu'une simple idée, probablement un peu folle ! ^^'

**Comment by Maxs1789** [comment]
Autre détail que je n'avais pas bien compris hier, la fonction standard `require` de Lua remplace les simple `.` par des `/` (c'est pour ça que la syntaxe `./fichier` ne fonctionne pas), ce qui permet par exemple de faire :
```lua
-- charge le fihcier /usr/local/share/lua/5.1/ma_lib/mon_fichier.lua
-- ou /usr/local/share/lua/5.1/ma_lib/mon_fichier/init.lua
require("ma_lib.mon_fichier") 
```
Mais de la même manière que pour les `..`, dans __Solarus__ ce code produit une erreur.

**Comment by christopho** [comment]
Closing this issue since almost all these examples are actually normal cases.

Except replacing "." by "/" which is not done. Feel free to open a separate issue for that if you think this is necessary.

The "../" syntax is blocked to prevent from getting outside of "data" in paths that are relative to the quest.
(But people can still see outside "data" with usual Lua file features. All Lua libs are available.)
