### ISSUE TITLE
Request: add method hero:get_sprite() or hero:synchronize(sprite)

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#669]
At this moment there is no way to synchronize the sprite animation of the hero with other, since this sprite cannot be recovered. Add some method hero:get_sprite() or hero:synchronize(sprite).

**Comment by Diarandor** [comment]
I was thinking that the method hero:get_sprite() is the best solution, since it also allows to synchronize another sprite with the sprite of the hero. (So forget about the method hero:synchronize(sprite).)

**Comment by christopho** [comment]
The hero has several sprites, so there would be functions hero:get_tunic_sprite(), hero:get_sword_sprite(), hero:get_shield_sprite(), hero:get_shadow_sprite(), etc.
I am not sure if this is very useful indeed.

About the sprite:synchronize() feature, this feature might actually disappear in a future version. Because since Solarus 1.2, sprites that have the same frame delays are correctly synchronized. Before that, there were precision issues in the main loop and this is why there was this sprite:synchronize() method.

**Comment by vlag** [comment]
I know that this issue will be closed soon, but what about something like a hero:get_sprite(action) function ?

**Comment by Diarandor** [comment]
Yes, you're right, the method to synchronize could be unnecessary for most of quest makers (it would be useful only for certain purposes, when entities are created dinamically). But with the methods sprite:get_frame() and sprite:set_frame() one can synchronize two sprites anyway...

**Comment by christopho** [comment]
So are you saying we can should keep the synchronize() method for comfort? I might agree then.

**Comment by Diarandor** [comment]
I meant that I do not mind to keep or not the method synchronize since it can be remade using the methods sprite:get_frame() and sprite:set_frame(), if I am not wrong.

On the other hand, the methods hero:get_tunic_sprite(), hero:get_sword_sprite(), etc, can be quite useful for other (maybe unusual) purposes, such as mine, which is the following:

I am working on a hybrid game, something between "Link's awakening" and "The Lost Vikings 2". The second game (maybe you do not know it) has three characters with different habilities and you can switch between them whenever you want. 

In my game, when you switch between heros, the main hero entity and the custom entity of the other hero interchange their position, animation sets, sprites, etc. In particular, it would be nice to preserve the animations when switching, if possible (for example, if you switch heros in the middle of an attack). To do this, I need to use some synchronization methods on the sprite of the main hero (and the other custom entity), but this is not possible with the hero at the moment, if I am not wrong.

**Comment by Diarandor** [comment]
Also, having access to the sprite of the tunic of the hero would be useful  to use the event  on_animation_finished() of the tunic sprite. (The same with the sword sprite, etc.)

**Comment by Diarandor** [comment]
I found another nice use for the method hero:get_tunic_sprite() if it is implemented. To program the jump, and even allowing to use some weapon on the air, I think the best way is to shift the sprite of the hero with the set_xy() function, which cannot be done yet.

**Comment by christopho** [comment]
Agreed.

**Comment by christopho** [comment]
Yet another use case for hero:get_tunic_sprite(): detecting the changes of direction (with sprite:on_direction_changed(), useful to overwrite them for example to keep the direction fixed.

**Comment by Diarandor** [comment]
Another posibility for the syntax would be hero:get_sprite(sprite_name), which would shorten the API.
We would call: hero:get_sprite("tunic"), hero:get_sprite("sword"), hero:get_sprite("shield"), etc.

**Comment by christopho** [comment]
Agreed, and it would be nice to have the same get_sprite() method for all types of entities. get_sprite(name) could also work for enemies and custom entities.

**Comment by christopho** [comment]
entity:get_sprite() now works for all types of entities, including the hero, and takes an optional name parameter.
The doc states the names of all hero sprites: http://www.solarus-games.org/doc/1.5/lua_api_hero.html#lua_api_hero_overview_sprites
