### ISSUE TITLE
CMake fails to find SDL2MAIN_LIBRARY

### ISSUE THREAD

**Issue by strycore** [christopho/solarus#673]
When building the engine on Fedora 21 and after installing that dependencies, CMake would still complain about not being able to find SDL2MAIN_LIBRARY

    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    SDL2MAIN_LIBRARY
    linked by target "solarus_testing" in directory /home/strider/Games/zelda-mystery-of-solarus-dx/src/solarus/tests

I googled for this issue and found a similar one here: https://github.com/Aloshi/EmulationStation/issues/205. I did the exact same thing as suggested in this issue and removed SDL2MAIN_LIBRARY in  tests/CMakeLists.txt resulting in a successful build. 

The last comment states that this can break the build process on Windows and gives a fix.

**Comment by christopho** [comment]
It seems that we should put SDL2MAIN_LIBRARY in the CMake configuration only on Windows (and maybe on Mac OS?).

**Comment by christopho** [comment]
Fixed.
I removed the SDL2MAIN_LIBRARY dependency in the cmake configuration. Actually, it was already removed from the Solarus library and the Solarus executable, but was still there for unit tests.
It compiles fine on Windows, tested with gcc 4.8.
Thanks for the report!

**Comment by christopho** [comment]
Reopening because SDL2MAIN_LIBRARY was put back, necessary for some Windows unit tests.

**Comment by ranjak** [comment]
CMake configuration on Fedora (24) is broken again.
Maybe tests should link against SDL2MAIN_LIBRARY only on Windows ? I'll remove the reference and see if it works.
