### ISSUE TITLE
Error when creating custom entity dinamically without giving width and height

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#680]
When I try to create a custom entity dinamically (from some script), if the width or height are not given, there is an error and the entity is not created. I did not have this problem with Solarus 1.3, and in the Lua API of Solarus 1.4 it says that the width and height parameters are optional.

For example, in my error.txt file, it appears:
"Error: In maps/levels/left: [string "maps/levels/left.lua"]:5: bad argument #1 to create_custom_entity (Bad field 'width' (integer expected, got nil))"

**Comment by christopho** [comment]
Fixed in 1.4.1.
