### ISSUE TITLE
Bug: tunic sprite changes when the sword is obtained

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#681]
When the hero obtains the sword (from a chest or from the ground), the sprite of the tunic is changed (to the default one, I think). I don't have this problem when the bow is obtained, so maybe this  issue is only related to the sword (although I am not sure).

I am using Solarus 1.4, and I didn't have this problem with Solarus 1.3.

**Comment by christopho** [comment]
Fixed, but the problem was already present in 1.3.
