### ISSUE TITLE
Crash with entity:remove()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#690]
I have a problem when removing an entity. When it happens, solarus crashes (in a window it says that solarus stopped running) and the file error.txt is not created. To reproduce the bug, in the script of a custom entity, write:

local entity=...
function entity:on_created()
  local hx,hy,hz = self:get_map():get_hero():get_position()
  local other = self:get_map():create_custom_entity({direction=0,layer=hz,x=hx,y=hy})
  other:remove()
end

**Comment by Diarandor** [comment]
Do you have the same problem? I can also reproduce the crash with a switch on the map script:
```
function switch:on_activated()
  local hx,hy,hz = map:get_hero():get_position()
  local other = map:create_custom_entity({direction=0,layer=hz,x=hx,y=hy})
  other:remove()
end
```

**Comment by Diarandor** [comment]
I have realized that this crash only happens if the custom entity has been created on layer 0. (If the layer is 1 or 2 I don't get a crash.)

**Comment by Diarandor** [comment]
I have been testing this bug again. To reproduce it you must walk in the place where the custom entity was created and destroyed (that is probably why it only happens if the layer is the same as the ond of the hero). Sometimes it is harder to reproduce the crash than others (you may need to push the button several times, and then walk in the coordinates where the entity was created and destroyed).

**Comment by christopho** [comment]
Thanks for the details. This should help us to fix it.

**Comment by christopho** [comment]
I tried to reproduce the crash, without success so far. I made a simple map with a walkable switch that deactivates on leaving, and applied the code you sent.
I walked a lot of times on it, I have no crash and valgrind reports nothing.

Maybe you should send me your data?

**Comment by Diarandor** [comment]
I have tried to reproduce the crash using the sample quest and it does not happen, so this must be something related to some of my Lua scripts and not a bug of the engine. Sorry for the inconveniences if there is no bug.

(I have disabled almost all my scripts and I think that the cause of the problem is in the HUD script, because if I disable it there is no crash, although I do not know yet why it happens.) In any case, I can send you the data.

**Comment by christopho** [comment]
When a quest script does something wrong, the engine should show an error message and never crash, so there is a real bug. Can you send me your data at christopho@solarus-games.org? Thanks

**Comment by Diarandor** [comment]
Ok

**Comment by christopho** [comment]
I was able to reproduce the crash and I am working on it. Thanks!
