### ISSUE TITLE
Possible bug. Destroy entities when map:on_finished() has finished

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#691]
When the event "function map:on_finished()" is called, the entities of the map are already destroyed, so I cannot get the information I need. (You can check this using "if map:has_entity("...") then sol.audio.play_sound("...") end" inside the event.) The entities of the map should be destroyed when this event has finished, and not before.

I am using Solarus 1.4.2. (This is weird because I did not have this problem with Solarus 1.4.0. Has something been changed?)

**Comment by christopho** [comment]
Nothing has changed in this area between 1.4.0 and 1.4.2. Are you absolutely sure that the problem was not present in 1.4.0 and is present in 1.4.2? Can you double-check?

Anyway, you are right, entities should still exist when map:on_finished() occurs.

**Comment by Diarandor** [comment]
You are right, the problem was present in 1.4.0. It was then in 1.3.x when this problem was not present.
