### ISSUE TITLE
Add PNG files from the editor

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#694]
Feature request from ZoriaRPG:

Add a PNG resource file, for use with sprites/tiles, from inside the Solarus editor.

Place a button 'add' in the sprites editors, select a file from anywhere on the local volume. Then, Solarus copies it into the required directory, and assigns it a name matching the resource ID a user provides.

That would be simpler than manually going to the resource directory, copying, renaming it, and ensuring that it matches.

**Comment by Nate-Devv** [comment]
Is this a feature request for the editor or the engine?  It sounds like an editor feature request.

**Comment by christopho** [comment]
Ooops! Yes.
