### ISSUE TITLE
Slowness when changing maps with immediate transition

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#695]
Bug report from ZoriaRPG:

A bug that I, and several mates have noticed (on different hardware), is that during area transitions that do not have a cross-fade, there is about a 1.5 second delay, while Solarus loads the map for the next screen area, in which the game jitters, and the music halts briefly.

We suspect, this to be caused by the Solarus engine, not pre-fetching the next map area, and I have a suggestion for how to fix this: Find the closest map area to where the player is at all times, and keep that loaded in memory, so that the game engine can instantly transition to it. This is relevant only to map areas, where there are screen region transitions.

Clearly, you would only need to pre-fetch touching map areas, and probably only those to which the player is close. Maybe within X pixels of a boundary, to avoid that lag.

**Comment by christopho** [comment]
The performance of loading maps was improved a lot in past releases.

It is not clear whether the slowness you have is due to file accesses. There can be other bottlenecks like initializing sprites, initializing tiles, calling Lua code. So we need some profiling before any action.

Currently, I don't reproduce the problem at all, probably because of recent hardware. I put a transition of type "immediate" in ZSDX outside maps. Transitions are immediate, I don't even hear at all the music halt, even briefly.

The 1.5 second delay you report is huge. What kind of hardware do you use? Did you compile the engine yourself? If yes, did you compile in release mode? Do you use LuaJIT or regular Lua? Do you still have the problem if you play with a data directory instead of a data.solarus archive?

**Comment by christopho** [comment]
Closing the bug since we cannot reproduce it. Please reopen I you have more information to reproduce it.

**Comment by christopho** [comment]
According to the description, this was most likely caused by #723.

**Comment by DavidKnight247** [comment]
I found this issue with stuttering of music between areas on the GCW0 port. I solved it by increasing the sound buffer to first 8192 then 16384.

**Comment by christopho** [comment]
@DavidKnight247 A pull request is welcome

**Comment by DavidKnight247** [comment]
Imo it's not exactly an elegant solution but I'll happily submit a pull request.
