### ISSUE TITLE
Sample quest of 1.4 has format 1.5

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#696]
If you download the source code of Solarus 1.4.2, the sample quest does not work:

solarus_run ./sample_quest/
Solarus 1.4.0
Opening quest './sample_quest/'
2D acceleration: yes
Fatal: This quest is made for Solarus 1.5.x but you are running Solarus 1.4.0
Abandon (core dumped)

**Comment by christopho** [comment]
This was only a packaging issue. The source code downloadable archive was actually generated from 1.5 (development version) instead of 1.4.2. This is now fixed on the website.

@Nate-Devv if you downloaded the .tar.gz from the website to generate 1.4.2 packages, then they are probably wrong. Actually, zsdx 1.10 and zsxd 1.10 cannot only work with Solarus 1.4.
To check that you have the correct source code:
- sample_quest/data/quest.dat should say format 1.4
- include/solarus/Common.h should say version 1.4.2

**Comment by Nate-Devv** [comment]
I manually modified the sample quest data in my package versions.  I didn't know that zsdx and zsxd had that error, I'll fix that when I have the chance.

**Comment by Nate-Devv** [comment]
I now know what you meant for the package versions.  Yes I have the wrong versions.  That will be fixed.

**Comment by Nate-Devv** [comment]
I was compiling the actual 1.4.2 provided on the website.  The tests failed (one it seems). I can debug them later if you would like.

**Comment by christopho** [comment]
For information:

The git tag "v1.4.2" points to a wrong commit (of branch 1.5), this explained my error. Since published tags should not change, I created another tag "v1.4.2-correctcommit" that points to the correct commit. Sorry about that!

**Comment by neagix** [comment]
can you remove the wrong tag? this information is currently buried on a closed issue.

also currently it's not possible to use both masters, same error.

**Comment by Nate-Devv** [comment]
I'm actually not sure that you can remove the tag.  The tagged source is now available on the official website, so it shouldn't be a problem for users of the stable version.

**Comment by christopho** [comment]
Removing a tag after it was published is not recommended by git.
What is wrong with both masters? The sample quest version is correct on master (1.5).
