### ISSUE TITLE
Bluetooth gamepads do not work in Windows

### ISSUE THREAD

**Issue by Fordi** [christopho/solarus#697]
Specifically, when tested with my NES30, it works when the joypad is in USB mode, but not in BT mode.  Additionally, my OUYA joystick does not work in Solarus.  Both of these devices have been tested and work properly in other games.

If you need additional information, please ask, but I'll need guidance to get any kinds of hardware dumps for you.

**Comment by christopho** [comment]
Solarus uses SDL2 to handle gamepads and we have absolutely no control on what is detected or not. Do these other games also use SDL?

**Comment by Fordi** [comment]
Hm.  Not to my knowledge.  I'll do some tests against SDL2 reference code
to verify, then close and post a bug to them.
