### ISSUE TITLE
Bug with custom_entity:set_can_traverse_ground()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#698]
In the Lua API, for the function 
```custom_entity:set_can_traverse_ground(ground, traversable),```
it says that the parameter ground is optional. However, I get an error if I call ```custom_entity:set_can_traverse_ground(true).```
The error I get says: "bad argument #1 to set_can_traverse_ground (number expected, got boolean))"

**Comment by christopho** [comment]
There was a mistake in the documentation. The ground is not optional.
Additionally, the error message was wrong, it should say "string expected, got boolean", this is fixed too.
Thanks for the report!
