### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#706]
I have the following code in one of my game's dungeons, and when it gets to this point in the game, it crashes with a Segmentation Fault:

Map 205, Beginning Line 184 (full code available at https://github.com/wrightmat/zbom): 
for enemy in map:get_entities("keese") do
  enemy.on_dead = function()
    if not map:has_entities("keese_rupees") and not game:get_value("b1119") then
      chest_rupees:set_enabled(true)
      bridge_rupees:set_enabled(true)
      sol.audio.play_sound("chest_appears")
    end
  end
end

I haven't changed anything with this code recently, and the fault would've just started appearing in Solarus 1.4(.2?)

**Comment by christopho** [comment]
@wrightmat I cannot reproduce the crash for now. I tried with solarus 1.4.2 and solarus master, using your current git (919e643).
Do you have the crash as soon as you enter the map ?

**Comment by christopho** [comment]
I also tried to kill a keese, and I had no problem.

**Comment by wrightmat** [comment]
It happened the first couple of times when I killed the keese. I did get it once just walking around the map, so I don't know what caused that. Maybe it's a problem with the keese script and not the map?

**Comment by christopho** [comment]
Can you confirm if you reproduce it with the commit 919e643 or with a previous one?

**Comment by wrightmat** [comment]
Still present with current git. I placed print statements after each of the lines in that block and everything fires before the seg fault - both entities are enabled and the sound it played (although I don't hear it before it crashes).

**Comment by christopho** [comment]
You mean with current git of zbom or Solarus?

**Comment by wrightmat** [comment]
Sorry, current zbom. I have been working with stable Solarus 1.4.2 since it was released, and not the git releases.

**Comment by wrightmat** [comment]
It's not just the code above. On my current play through, where I'm over halfway through my game, I've gotten 4 seg fault crashes. Is there a memory leak or something maybe? Is there any way I can help trace this myself?

**Comment by christopho** [comment]
Did you have these crashes always at the same locations?
About tracing them yourself, I think this is possible to get stack dumps when a process crashes on windows, but I don't know how exactly.

**Comment by christopho** [comment]
Another question: does it crash when running the game from the editor or with solarus_run.exe or both?

**Comment by christopho** [comment]
Can you send me a savegame file that makes the crash? Maybe there is something different in mine that avoids problematic code.

**Comment by christopho** [comment]
When you say you got 4 other crashes, did they happen on this map 205 as well?

**Comment by christopho** [comment]
@wrightmat Are you using linux? If yes, you should be able to dump a strack trace that might help. Install the GDB debugger and attach it to the solarus process. To do that, run solarus normally and then, when it is running, type from a terminal:

    $ gdb -p $(pgrep solarus)

Now, solarus is attached to gdb and is suspended. To continue the process, type c in the gdb console. Now you can play normally until it crashes. When it crashes, gdb says that there is a segmentation fault and you can type commands in the gdb console again. Type bt in the gdb console. This outputs a stack trace which is the information I need. If you can get it and copy-paste here, this should be helpful.

**Comment by christopho** [comment]
I also had a segfault in your game, when walking on a star switch in the ice temple. I played zbom at commit 3dd5791, with Solarus 1.4.2 release compiled with LuaJIT.
I am trying to reproduce it again, without success so far.

**Comment by wrightmat** [comment]
I had a seg fault there as well, and am currently unable to complete the dungeon because it is being reproduced. I do usually play in Linux, so I'll try the gdb method above. I'll also email you my save file when I get home from work.

**Comment by wrightmat** [comment]
In map 209, when stepping on the star switch (the one you had as well):

Program received signal SIGSEGV, Segmentation fault.
0x00007fa2462eeaf6 in Solarus::MapEntity::update_ground_observers() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
(gdb) bt
#0  0x00007fa2462eeaf6 in Solarus::MapEntity::update_ground_observers() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#1  0x00007fa2462f0156 in Solarus::MapEntity::notify_position_changed() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#2  0x00007fa246345e41 in Solarus::LuaContext::entity_api_set_position(lua_State*) () from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#3  0x00007fa244a8ba9b in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#4  0x00007fa244aced00 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x00007fa2463950c7 in Solarus::LuaTools::call_function(lua_State*, int, int, char const*) () from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#6  0x00007fa2463642db in Solarus::LuaContext::switch_on_activated(Solarus::Switch&) () from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#7  0x00007fa2462fc294 in Solarus::Switch::try_activate(Solarus::Hero&) ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#8  0x00007fa2462d4487 in Solarus::Detector::check_collision(Solarus::MapEntity&) () from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#9  0x00007fa246407b1e in Solarus::Map::check_collision_with_detectors(Solarus::MapEntity&) () from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#10 0x00007fa2462f0063 in Solarus::MapEntity::check_collision_with_detectors()
    () from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#11 0x00007fa2462e0806 in Solarus::Hero::check_position() ()
from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#12 0x00007fa2462e0ade in Solarus::Hero::notify_position_changed() [clone .localalias.64] () from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#13 0x00007fa2463db639 in Solarus::Movement::set_xy(Solarus::Point const&) ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#14 0x00007fa2463db6a3 in Solarus::Movement::set_xy(int, int) ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#15 0x00007fa2463e1db6 in Solarus::StraightMovement::update_smooth_y() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#16 0x00007fa2463e2087 in Solarus::StraightMovement::update() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#17 0x00007fa2463e014e in Solarus::PlayerMovement::update() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#18 0x00007fa2462dfba3 in Solarus::Hero::update_movement() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#19 0x00007fa2462e48b1 in Solarus::Hero::update() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#20 0x00007fa2462eab48 in Solarus::MapEntities::update() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#21 0x00007fa246406c8a in Solarus::Map::update() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#22 0x00007fa24640200c in Solarus::Game::update() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#23 0x00007fa246402cff in Solarus::MainLoop::update() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#24 0x00007fa24640348e in Solarus::MainLoop::run() ()
   from /home/mwright/Downloads/solarus-1.4.2/build/libsolarus.so
#25 0x000000000040133b in main ()

I also emailed you my save file.

**Comment by christopho** [comment]
I still have a very hard time trying to reproduce the crash, but I have fixed two crashes related to grounds in 1.4.3. This one might be solved.

**Comment by christopho** [comment]
@wrightmat 1.4.3 was just released, can you see if the crash is fixed after recompiling from the git tag v1.4.3?

**Comment by wrightmat** [comment]
I can no longer reproduce this error, so I believe it is fixed. Thanks, and closing!

**Comment by christopho** [comment]
\o/
