### ISSUE TITLE
Possible bug with game:on_dialog_finished()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#709]
I have defined in the game manager file:
```
function game:on_dialog_finished()
-- Some code... or nothing!
end
```
What happens next, after a dialog, is that the dialog box does not dissapear, it is still drawn but the game is unpaused. This happens if the event is defined. If the action key (or the attack key) is pressed, I get the error "Cannot stop dialog: no dialog is active". (I have tried to use "game:stop_dialog()" inside the event, but the same error appears.)

**Comment by christopho** [comment]
I need more details to reproduce the problem. For example in ZSDX, this event is defined but there is no problem.
Do you have a scripted dialog box or do you mean the built-in one?

**Comment by Diarandor** [comment]
I am using a scripted dialog box. Maybe it's a problem of the script (I will try to check this).

**Comment by Diarandor** [comment]
Yes, you are right, that function was already defined in the script of the dialogs (I was using the one you made), so I was overriding it in the game manager script, which produced the problem.

So there is no bug, you can close the issue. Sorry for the inconvenience.

**Comment by christopho** [comment]
No problem!
