### ISSUE TITLE
Custom entity collision callback still called after entity is removed

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#710]
This bug can be reproduced with https://github.com/christopho/zelda_mercuris_chest/commit/6804e8bf0ee91f5286bd7640aa9dcd90e83144b4

In the cane_of_medusa item script, the callback is triggered twice, even though the enemy is removed the first time.

**Comment by Nate-Devv** [comment]
This is still present in later Mercuris Chest commits?

**Comment by christopho** [comment]
No, I used a workaround in Mercuris' Chest, before I fix it.
See line 58 of https://github.com/christopho/zelda_mercuris_chest/commit/ff9d43a7081a0266126e8680c7640a80782f2a31

**Comment by Nate-Devv** [comment]
Ok.

**Comment by christopho** [comment]
Fixed in commit 5987347.
