### ISSUE TITLE
Map:on_draw persists after map

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#711]
If a map entity is referenced from map:on_draw, and the hero changes map, an entity is nil error will throw at least once on the new map. Nothing in this function should fire after the map changes.

**Comment by christopho** [comment]
It seems that map:on_draw() is called one more time after the map is finished. Entities are already destroyed at this point.

**Comment by christopho** [comment]
I cannot reproduce the bug, I think it is already fixed.
Please reopen with more details if you still have the problem.
