### ISSUE TITLE
OpenAL Soft support

### ISSUE THREAD

**Issue by daniloegea** [christopho/solarus#714]
Do you have plans to support OpenAL Soft instead of the old OpenAL? I'm linking Solarus with OpenAL Soft on FreeBSD (the default openal on Port) and I'm getting a segmentation fault when audio starts. I can provide more details if necessary.

**Comment by christopho** [comment]
I did not know that there was an OpenAL Soft.
Yes, if you have more details (ideally a callstack) this can help.

**Comment by Nate-Devv** [comment]
From the debian package page for libopenal1 (Openal Soft):

OpenAL Soft supports mono, stereo, 4-channel, 5.1, 6.1, and 7.1 output, as opposed to the SI's 4-channel max (though it did have some provisions for 6 channel, this was not 5.1, and was seemingly a "late" addition). OpenAL Soft does not support the Vorbis and MP3 extensions, however those were considered deprecated even in the SI. It does, though, support some of the newer extensions like AL_EXT_FLOAT32 and AL_EXT_MCFORMATS for multi-channel and floating-point formats, as well as ALC_EXT_EFX for environmental audio effects, and others.

**Comment by daniloegea** [comment]
The stack trace: http://pastebin.com/q8a36aUA

**Comment by daniloegea** [comment]
The problem seems to be in openal-soft+clang. It just works with gcc and crash with clang. Sorry for the noise.
