### ISSUE TITLE
sol.input.get_mouse_position ignores the window zoom factor

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus#734]
the events `on_mouse_pressed()` and `on_mouse_release()` take into account the window zoom factor but not the function `sol.input.get_mouse_position()`.

example: 
```lua 
function menu:on_mouse_pressed(button, x, y)
  print("mouse pressed!")
  print("  event:", x, y)
  print("  sol.input:", sol.input.get_mouse_position())
end
```

outputs (with zoom factor of 2 and a quest size of `320x240`):
```
mouse pressed!
  event:        23      17
  sol.input:    46      34
mouse pressed!
  event:        134     55
  sol.input:    268     110
mouse pressed!
  event:        176     131
  sol.input:    nil
```

**Comment by christopho** [comment]
Keeping the bug open, we need to test it on Windows.

**Comment by vlag** [comment]
I checked on OSX in the meantime and I can get different values when the viewport don't start at 0, 0 : 

![capture d ecran 2015-08-30 a 11 19 11](https://cloud.githubusercontent.com/assets/4290534/9566530/4f719c22-4f09-11e5-99c8-7adbce6eb35d.png)


I didn't checked further but why was it necessary to split the Video::get_scaled_position into 2 other method ?
SDL_GetMouseState() and internal_event.button would not return the same value and I missed it ?

**Comment by christopho** [comment]
With SDL 2.0.2 on linux, SDL_GetMouseState() and internal_event.mouse give different values. One is in viewport coordinates and the other one in window coordinates.

**Comment by christopho** [comment]
Works as expected on windows with current dev branch.
