### ISSUE TITLE
Lua doesn't output to command prompt in Windows

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#735]
Windows doesn't output to command prompt like Linux/Mac does to console, which makes development on Windows much more difficult. Might something like this be helpful? https://gist.github.com/5at/3671566

**Comment by Renkineko** [comment]
There is an option (not well documented because I had to look up the C++ code of the engine to find out what it is :p ) when you launch the game via the console : run_solarus.exe -win-console=yes [your quest]

**Comment by christopho** [comment]
Or if you run from the editor, there is a checkbox to activate the console in the preferences.
