### ISSUE TITLE
Some teleporters are disabled

### ISSUE THREAD

**Issue by Renkineko** [christopho/solarus#736]
From hermier, in zelda-roth, some teleporters don't work anymore : it seems the cause is the teleporter is too long (the one on the left side of the screen where the ice dungeon is can be used to see that) and is considered too far away from the camera, so it's disabled.

**Comment by Renkineko** [comment]
Already solved in a revert

**Comment by christopho** [comment]
I reverted 7e7a240 and 70ad052 in master, they are too dangerous, and I am now working on performance with them in a separate branch.
