### ISSUE TITLE
Is custom_entity:on_interaction() working correctly?

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#741]
Hi, I am trying to use the event custom_entity:on_interaction(), but nothing happens. I put a sound inside the event but it is not played when I press action command facing the custom entity. I have tried with traversable and non-traversable custom entities. I am aware that this was in the list of fixed bugs in version 1.2.1, so maybe I am doing something wrong (but it still could be a bug).

**Comment by christopho** [comment]
It works in zelda roth se, at least: https://github.com/christopho/zelda_roth_se/blob/master/data/entities/zelda.lua
And it works for both traversable and non-traversable custom entities.

**Comment by Diarandor** [comment]
Yes, you are right. I have realized now that if I don't define the function game:on_command_pressed(command) the event works.

So the problem is that I was already defining an action when the action effect variable is nil, which was obstructing the interaction with the custom entity. I will solve this by setting a custom action effect different from nil for these events.

Thank you!

**Comment by christopho** [comment]
Ok, the game command propagation was stopped in your game:on_command_pressed() event. Return false or nil to continue the propagation.

**Comment by Diarandor** [comment]
That would work. But still, I will solve it in a different way, since I have a different behavior for the action command when the action command effect is nil (I use it to switch from one hero to another). I should not have problems to solve it. Thanks for your help!
