### ISSUE TITLE
Request: event custom_entity:on_interaction_possible()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#742]
Add event "custom_entity:on_interaction_possible()", which is called when the hero can interact with the custom entity.

I point out that using collision tests to notify the hud that the hero can interact with the custom entity would not be perfect, since the test would not be the same that the engine uses, so it could happen that the hud is notified when the interaction is not possible or that the hud is not notified when interaction is possible.

**Comment by christopho** [comment]
custom_entity:add_collision_test("facing", ........) is equivalent to what the engine does with NPCs.

**Comment by Diarandor** [comment]
Ok, thanks! Then I close this useless issue.
