### ISSUE TITLE
Request: function entity:has_collision(collision_test, other_entity)

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#748]
It would be nice to be able to use the tests of the engine used to detect collisions in the function custom_entity:add_collision_test(collision_test, callback). 

To detect if two given custom entities are in collision (relative to some collision test) at a precise moment, it is not a good idea to add a collision test since you need to check the collision just once and you know when. It would be better to call the corresponding collision test function.

This is not possible yet, I think, except for the function entity:overlaps(other_entity), which is the test function used in the method custom_entity:add_collision_test("overlapping", callback). But, for instance, we do not have a method like entity:is_facing(other_entity), etc.

To make the syntax simpler, I would suggest to have a function like: entity:has_collision(collision_test, other_entity), or something similar, where collision_test is a string representing one of the collision test functions used by the engine (which are not directly accesible at present), like "facing", "touching", "containing" and "sprite".

**Comment by Nate-Devv** [comment]
Good idea! It seems that this will add consistency to the API too!

**Comment by christopho** [comment]
Agreed, I don't know why we did not think of that before.

**Comment by Diarandor** [comment]
Could this be added to Solarus 1.5 or 1.6?

This would really come in handy when we need to check if one entity is facing other one at some instant (and other similar situations), and adding a collision test for that purpose as a workaround is very annoying... I will have to define my own collision function using the bounding boxes for that purpose, but it would be better to use the functions of the engine, although this is just my opinion.

**Comment by christopho** [comment]
Ok, we can do this for 1.5.

**Comment by christopho** [comment]
I finally did it as a new parameter to entity:overlaps(other_entity).
Now entity:overlaps(other_entity) without second parameter means entity:overlaps(other_entity, "overlapping"), and you can also test "containing", "origin", "center", "facing", "touching" and "sprite".
