### ISSUE TITLE
Impossible to push a statue after having pulled it

### ISSUE THREAD

**Issue by Morwenn** [christopho/solarus#757]
With the current master, I pulled the statue in ZSDX's first cave half a case to the South (you can't pull it more) but I wasn't able to push it after that. This seems to be a regression since the problem wasn't present in older versions of the game. I didn't try with other directions nor with full cases.

**Comment by christopho** [comment]
Ok in 1.4, broken in master.

**Comment by Morwenn** [comment]
Update: still broken, but maybe differently. Now, after having pushed or pulled a statue, I can sometimes walk through it, which means that I can't push/pull it anymore when I walk into it from a given direction (I couldn't really identify patterns though). I still acts as a tangible item when I walk into it from some directions.
