### ISSUE TITLE
Addition to hero:get_state()

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#774]
hero:get_state() would be even more useful if, instead of returning "free", the engine returned "walking" when the hero was walking and "stopped" when the hero was not walking. This would allow for changes to the hero animations that are currently more difficult.

**Comment by Diarandor** [comment]
But you can use hero:get_animation(), or even make your own function fully customizable to get the state. I think this request is not necessary, but this is just my opinion.

**Comment by Diarandor** [comment]
Now we can access to the tunic sprite of the hero (see https://github.com/christopho/solarus/issues/669). Hence, we can get the name of its animation, and we also have access to all of the events of the tunic sprite (like on_animation_changed, etc). So I think that you can now do whatever you want related to this issue, if I am not wrong.

So I think we can now close this issue, do you agree?

**Comment by Renkineko** [comment]
Not sure: if the hero is freezed by the game, the sprite is not modified : it's still the standing animation, but the hero is not free to go wherever he wants. Still think this feature may be useful.

**Comment by christopho** [comment]
But then he is in state "frozen", not "free". So yes, we can close this issue.

**Comment by Renkineko** [comment]
Misread the issue first, sorry :) I agree.
