### ISSUE TITLE
Feature request: allow to change default tunic animations for built-in states of hero

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#778]
Sometimes, it would be useful to change temporarily some animation of the current tunic sprite of the hero for a different one. The aim of this request is mainly to allow changing the stopped/walking animations of one tunic, maybe temporarily, without need of creating a new tunic in the sprite editor. We could use a function like:

```sprite:replace_animation(state, new_animation_name)```

to change/replace (maybe temporarily) some default animation with another. 

The first parameter "state" refers to the built-in state of the hero (like walking, swimming, stopped or falling) to indicate that we are changing the default animation corresponding to that state with a new one, whose name is given by the string in the variable "new_animation_name". Note that to restore the original animation it would suffice to write:

```sprite:replace_animation(state, state)```

because the name of the state coincides with the name of the default/original animation.

***************
Some uses this feature would be:

-The main use would be to allow to walk sideways / sidle. For instance, while using the shield and/or some weapons like the bow (when holding pressed the corresponding item button). This would allow to protect the hero while walking sideways in the case of the shield, and aiming while walking sideways in the case of the bow. I'm sure that other game makers would be interested in the feature for this purpose.

-Allowing to change temporarily the walking animations for something. This could be used, for instance, to make a blinking animation different from the one of the engine when the hero is hurt. (This kind of use would be something rare, probably.)

The next use is probably not important for other game makers, but a very important use I would give to this feature would be the following:

-For the game I am still working on, I wrote a script that allows to carry custom entities, which uses the trick of changing the tunic sprite to simulate the carrying animation when the hero is stopped/walking. But this has to be done with all tunics, so the number of tunic sprites I need to create in the Solarus Editor is the double of the tunics I use in the game. With this feature I can make my script easier to use for other people because it would not be needed to create additional sprites/tunics. (I would use this requested feature to replace the default stopped/walking animations with the carrying animations, temporarily.)

**Comment by christopho** [comment]
Did you try to call hero:set_animation() from hero:on_state_changed()?

**Comment by Diarandor** [comment]
That's a good idea. But still we have the problem that we cannot use the state to distinguish when the hero is walking or stopped, because in both cases the state is "free". There is an issue asking for this here:
https://github.com/christopho/solarus/issues/774

A different solution would be to define the event on_animation_changed of the tunic of the hero, since the name of the animation of the tunic sprite usually coincides with the name of the state of the hero. The problem in this case is that we still cannot have access to the tunic sprite; there is an issue for this here:
https://github.com/christopho/solarus/issues/669

Solving any of the two issues referenced above would allow to solve this issue (allowing to program the features I wanted, like walking sideways, etc).

**Comment by Diarandor** [comment]
This can now be done since we have access to the tunic sprite (see https://github.com/christopho/solarus/issues/669), so we can define the event on_animation_changed of the tunic sprite to keep a chosen tunic animation for a while: if the engine changes the animation, we restore the chosen animation, which can be done in the event on_animation_changed. 
(Remark: In a similar way this technique can be used to fix a direction on the hero to walk sideways).

I close the issue.
