### ISSUE TITLE
Entity already in Z cache error when using a Teletransporter

### ISSUE THREAD

**Issue by Morwenn** [christopho/solarus#781]
I just updated solarus and zsdx from their respective master branches and compiled solarus with MinGW GCC 5.2. I started at my old save point in the first cave in the village, and whenever I try to use a teletransporter, the game crashes with the error "Entity already in Z cache". Using stairs or falling to the level below still work fine; the error seems to be related to teletransporters.

**Comment by christopho** [comment]
The error seems to appear with teletransporters that send to the same map.
