### ISSUE TITLE
Bug: custom_entity:set_can_traverse_ground("traversable", false) does not work.

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#794]
If we write
```
custom_entity:set_can_traverse_ground("traversable", false) 
```
the custom entity can still traverse "traversable" grounds.

I need this to program a raft that can move over water, but not over "traversable" grounds.

**Comment by christopho** [comment]
"traversable", "wall", "ice" and "grass" were not working for custom_entity:set_can_traverse_ground(). This is now fixed in 1.5. Thanks for the report!
