### ISSUE TITLE
Bug: cannot destroy an entity and create a new one with the same name

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#795]
Using the event map:on_started, I created an entity with a given name. Then, if we destroy it and try to create a new entity with the same name, the name of the new entity is nil.

This is quite annoying, because sometimes we need to change a property of some entity and there is no function to do it, so we need to destroy the entity and create a new one with the new properties. But if the new entity has the same name as the old one, we cannot assign the name.

Could this be fixed for the next bugfix or next release?

**Comment by christopho** [comment]
Workaround: create it next frame, for example with a timer of delay 1.

**Comment by Diarandor** [comment]
Thanks! Your workaround works fine.

**Comment by christopho** [comment]
Ok, then I keep the issue open because it is still a bug, but it won't be fixed in 1.4.5.
