### ISSUE TITLE
sprite:on_animation_finished() not always called

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#799]
_From @Renkineko on August 12, 2015 19:31_

Dans le donjon 1 de zelda_roth_se, les squelettes ont de temps en temps (environ 1 fois sur 10) un comportement étrange : ils disparaissent après le premier mouvement (je pense même après l'animation où ils tournent la tête), mais les collisions restent : si on va sur l'emplacement où ils étaient on prend des dégâts et si on tape à l'endroit où ils ont disparu, ils réapparaissent (animation blessure), refont un mouvement et à la fin redisparaissent. Ils peuvent mourir normalement.

Pour le constater : faire des allers retours entre le sous-sol (où il y a la porte du boss) et la salle principale et observer les squelettes.

_Copied from original issue: christopho/zelda_roth_se#15_

**Comment by christopho** [comment]
_From @Renkineko on August 12, 2015 20:48_

Apparently, fix bff0c12 seems OK. Closing the issue, I'll reopen if I encounter the bug again.

**Comment by christopho** [comment]
_From @Renkineko on November 9, 2015 18:23_

I confirm the bug still exists with Solarus 1.4.5 after reverting bff0c12, good news : it happened on my ubuntu session (totally different pc), so it's not specific to the os nor my hardware (the only common is the hard drive where the quest is, not even the engine is on the same drive than my first encounter with this problem ^^), you should be able to do it. Nothing to see in the console when happened.

**Comment by christopho** [comment]
Thanks to Renkineko we have more information: in LuaContext::userdata_has_field(), userdata.is_with_lua_table() is false. Maybe the function on_animation_finished() is assigned too late on the sprite, its animation finishes immediately?

**Comment by christopho** [comment]
More information again (thanks @Renkineko): if we make LuaContext::userdata_has_field() just return true, the bug still exists.
So, sprite:on_animation_finished() is really not found for some reason, it is not a wrong behavior of userdata_has_field().

**Comment by christopho** [comment]
_From @Renkineko on November 23, 2015 23:13_

It's not a quest related issue: if you copy and paste the skeleton sprite and script on another quest (for my test, I imported them in my nrfh repository), the same issue happens. Maybe we should close the issue here and open the issue on the engine?

**Comment by christopho** [comment]
More progress!

    function sprite:on_animation_finished()
        ...
    end

    assert(sprite.on_animation_finished ~= nil)

This assert raises sometimes, this is the bug. There must be something wrong in the mechanism that indexes userdata.

According to @Renkineko, the bug disappears if you disable the Lua garbage-collector. So the problem might depend of when exactly garbage collection cycles happen.

**Comment by christopho** [comment]
This also explains a rare bug I had during a streaming, of the hero getting freezed after putting a bomb in Zelda Roth SE. The code does

    map.current_bombs = map.current_bombs or {}

but sometimes, map.current_bombs is nil after this line.

**Comment by christopho** [comment]
Should be fixed by https://github.com/christopho/solarus/commit/bae9f6f910883822da61207e1f95f13d54287bd4.
@Renkineko can you confirm? Thanks

**Comment by Renkineko** [comment]
It's fixed, as I said on irc :) enjoy


Envoyé via Outlook Mobile






On Mon, Nov 30, 2015 at 6:15 AM -0800, "Christopho" <notifications@github.com> wrote:





Should be fixed by https://github.com/christopho/solarus/commit/bae9f6f910883822da61207e1f95f13d54287bd4.
@Renkineko can you confirm? Thanks

---

**Comment by christopho** [comment]
Thanks again for your help!
