### ISSUE TITLE
[Feature request] Shared object versioning on UNIX

### ISSUE THREAD

**Issue by daniloegea** [christopho/solarus#800]
Hello, as I said few weeks ago, I'm maintaining solarus (and now solarus-quest-editor) for FreeBSD in our Ports tree. One useful feature I'd like to be added on solarus installer is the support for shared object versioning (solarus.so.x.y.z). Thus you can indicate an ABI breakage incrementing the .so numbers.

Example (AddSolarusLibrary.cmake):

set(solarus_VERSION_MAJOR 1)
set(solarus_VERSION_MINOR 4)
set(solarus_VERSION_PATCH 5)
set(solarus_VERSION_STRING ${solarus_VERSION_MAJOR}.${solarus_VERSION_MINOR}.${solarus_VERSION_PATCH})
set_target_properties(solarus PROPERTIES VERSION ${solarus_VERSION_STRING}
	SOVERSION ${solarus_VERSION_MAJOR})

With this, cmake will create links to solarus.so:
libsolarus.so@ -> libsolarus.so.1
libsolarus.so.0@ -> libsolarus.so.1.4.5
libsolarus.so.1.4.5*

**Comment by christopho** [comment]
Feel free to make a pull request!
