### ISSUE TITLE
Problem with "hero:teleport(map_id, "_sideX", "scrolling")" when scrolling to the right

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#806]
(EDIT: The previous thing I posted here was not the real problem, so I have changed this.)

Hi, I was trying to program something with the function "hero:teleport(map_id, [destination_name, [transition_style]])" using the scrolling transition style.

The function "hero:teleport(map_id, "_sideX", "scrolling")" does not seem to work when changing map to the right direction (I am walking to the right). I have tried to change the variable destination_name with all the possible values "_side0", "_side1", "_side2" and "_side3", but the hero always appear stuck in a corner of the map instead of appearing from the correct direction. I do not have this problem when going up, down or to the left.

**Comment by christopho** [comment]
It works for me. What is the location property of both maps?

**Comment by christopho** [comment]
Is there an error message in the console or in error.txt?

**Comment by Diarandor** [comment]
Ok, you are right, there is no bug. Sorry. I realized I was doing something wrong (by mistake I was setting the teleporting destination to "_side" instead of "_sideX", or something like that). I close the issue.
