### ISSUE TITLE
Request: add functions sprite:bring_to_front() and sprite:bring_to_back()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#809]
Add functions sprite:bring_to_front() and sprite:bring_to_back().

If the given sprite belongs to some entity (say, to a custom entity, to the hero, or to any other entity), then the methods above should make the sprite to be drawn before/after all the other sprites of the entity.

In case the sprite does not  belong to an entity (I don't know if this is possible now, but I suppose it will be someday), then these functions should work exactly as the entity functions entity:bring_to_front() and entity:bring_to_back().

**Comment by christopho** [comment]
Sprites are displayed in their creation order.
Maybe it can be useful to allow to change the order after their creation.

**Comment by Diarandor** [comment]
Yes. It could be useful to allow changing the order after creation of the sprites in the corresponding context (the map or some entity)
