### ISSUE TITLE
hero:on_state_changed(state) not working correctly?

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#814]
Maybe I am doing something wrong, but I think that this event is not always called. I think this event is not called when the hero starts swimming, or pulling a wall, or start carrying a built-in destructible, and other cases. Could someone confirm this problem?

**Comment by christopho** [comment]
Already fixed in https://github.com/christopho/solarus/commit/7a704de087930752adc5f907db2cda8e9f9b5737
(Only affected 1.5 dev branch)
