### ISSUE TITLE
entity:set_enabled(true) does not work if it blocks the hero

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#817]
When you enable an obstacle entity that overlaps the hero, it avoids to block the hero and instead waits for the hero to leave before getting enabled.
This is an old feature that does not make a lot of sense. If the user wants to do so, the script should do it.

See http://forum.solarus-games.org/index.php/topic,492.msg2365.html#msg2365

Fixing this problem will break compatibility because old games (like zsdx in dungeon 2) expect this behavior.

**Comment by Morwenn** [comment]
One place where it's almost aways a good idea to delay the enabling is with chests that appear once you fulfill a condition. I remember that it was among the things I tried while testing ZSDX and was surprised that the game was protected against this kind of things :)

**Comment by christopho** [comment]
The good news is that chests are already protected against this, they move the hero to the south if they appear on him.

**Comment by Morwenn** [comment]
Oh, of course it would work since you need to be South of a chest to open it. Simple and clean. I like that ^_^
