### ISSUE TITLE
Add property to destinations to ease saving starting position

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#819]
It would be useful, specially for the Editor, to have a property "save_starting" for destination entities. This variable could take the three following values:

1. "changing_world" (or nil). This should be the default value (to keep compatibility with the current engine and editor properties) and would update the starting position of the hero if and only if we are changing world when arriving to this destination.
2. "always" (or true). This will always update the starting position when arriving to this destination.
3. "never" (or false). This will never update the starting position when arriving to this destination.

Also we would need getter and setter functions to get and modify the value (from the map script) of this property of a given destination.

If you decide to add this customization property, do not forget to add this property to the Editor, which will be very useful for quest makers. (If you agree with this request, we should open an issue for the Editor too.)

EDIT: I am not sure if I will use this feature, so it's fine if you close this request it if you think it's not necessary.

**Comment by christopho** [comment]
Done!
