### ISSUE TITLE
Evaluate SDL_mixer support

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#820]
Using SDL_mixer instead of OpenAL would reduce dependencies and simplify code.
See if SPC musics can correctly be played with SDL_mixer.

**Comment by Morwenn** [comment]
If this can be done, I'm all for reducing the dependencies too. I still fear the day I will have to rebuild every dependency.

**Comment by NewLunarFire** [comment]
Built the project yesterday from Cygwin on W10 x64. The dependencies aren't large, but I couldn't find how to make cmake output all the missing dependencies. I think that's the largest issue with this.

No OpenAL specific code seems to reside within the SPC library, so I think switching to SDL Mixer shouldn't be an issue for the SPC library. The Vorbis library shouldn't be a problem either.

Looking at the source, the SPC library decodes the files into samples and those samples are sent to OpenAL. SDL Mixer has the same capabilities and gives access to their internal storage format (https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_frame.html).

Now to see who will tackle the dauting task of switching OpenAL code over to SDL_Mixer and making it all work together.

**Comment by christopho** [comment]
The reason why I switched from SDL_mixer to OpenAL (a long time ago) was because the output of the SPC decoder has a different sampling rate as the rest of the sounds, and SDL_mixer did not allow to mix different sampling rates.

**Comment by NewLunarFire** [comment]
I see, we'd have to write our own resampler or use an open-source one (like Soxr) to fix the issue, and that's introducing more dependencies or 3rd-party libs to the code.

It seems SDL_Mixer still does not support resampling at the moment.

**Comment by christopho** [comment]
Ok, thanks for the info. Closing the issue then.
