### ISSUE TITLE
Can lowlevel be licensed public domain / zlib / ISC / MIT / BSD?

### ISSUE THREAD

**Issue by tony** [christopho/solarus#826]
Thank you for your project @christopho. I'm playing solarus on FreeBSD and using the project as way to learn C++.

Are you willing to release lowlevel ([include](https://github.com/christopho/solarus/tree/dev/include/solarus/lowlevel), [src](https://github.com/christopho/solarus/tree/dev/src/lowlevel)) under zlib (same license as SDL2) or potentially spinning the library off into a zlib-licensed project of its own?

This part of solarus is different in it'd be very useful for SDL C++ projects / frameworks outside of the project.  If you're not able to license it I'd end up writing my own similar to how you did it in the end. :smile: I want to ask before potentially duplicating the effort.

**Comment by christopho** [comment]
Sorry, no, I don't want to separate the code in different licenses.
