### ISSUE TITLE
Add methods entity:get_ground_point() and entity:get_ground_below()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#830]
Hi, I was testing my scripted Pegasus boots. That script creates a movement on the hero, and the movement is stopped when bad ground (hole, deep water or lava) is detected under the hero. If I run into a hole from the left, right or down sides, the hero falls into the hole (because the movement is stopped when the position of the hero is over the hole), but that does not happen when running from "up" direction. In that case, the hero is stopped, but he does not fall. The ground detected under the hero (when the hero is stopped after approaching from up direction) is hole, but he does not fall. I have also checked that if the hero approaches the hole from down direction, he starts falling one pixel before the ground detected under him becames hole.

What I guess from all of this is that the collision with bad grounds is shifted 1 pixel down (I am assuming that the ground detection under the hero is correct). I think that this bug is important enough to be corrected before the Solarus 1.5 release, to avoid similar problems.

EDIT: I was checking the ground using a timer that is called each millisecond (and not when the position of the hero changes). But this probably does not matter.

**Comment by christopho** [comment]
The point used for ground detection is indeed different from the origin point. For the hero, it is (x, y-2).
This is because if we used the origin point, the hero would fall too easily in holes in the "down" direction.

So to get the ground below the hero like the engine does, call map:get_ground(hero_x, hero_y - 2).

Maybe there is something missing in the API to avoid such hardcoded value. We could add a function entity:get_ground_point() that return these coordinates, and a function entity:get_ground_below() that returns the ground for you. What do you think?

**Comment by Diarandor** [comment]
Thanks for the explanations. I was assuming that the detection of the ground under the hero entity corresponded to the ground of its origin, which is not true. I agree that the Lua API should explain a bit of this, to avoid this kind of confusion. I had some trouble some time ago when I was scripting moving platform entities (the problem was to delimit the border of the platforms with accuracy, just in case the platform changed the direction of its movement, which sometimes made entities fall into the bad ground under the platform if they were on the border), and I now realize that it was related to this issue.

I completely agree that both functions should be added to Solarus, which will solve all the problems. I guess that the difference between the origin and the ground position may be different depending of the size of the entity, so at present there is no way to know the ground point of an entity, because a quest maker does not know how that point is computed.

I will use the function map:get_ground(hero_x, hero_y - 2) as a workaround for the hero. When this issue is solved, we will be able to make a perfect behaviour for the moving platforms that move several kinds of entities (of different size).

**Comment by christopho** [comment]
Ok, let's do this for 1.5. Thanks for the feedback!
