### ISSUE TITLE
Bug: entity:set_enabled(false) not working

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#836]
I am calling "entity:set_enabled(false)" for some entities from the event "map:on_started()" and they are still visible, but stopped and there is no collision with them and the hero can traverse them. These entities should not be displayed.

I have checked this with custom entities, NPC's and enemies, but maybe this affects other entities too (untested).

**Comment by christopho** [comment]
Should already be fixed by commit 1154a461.
