### ISSUE TITLE
Add game description to the quest properties file

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#838]
To be able to display some information about each quest in the Solarus GUI, quest.dat should also contain
- The title of the game (mandatory)
- The author
- A short description of one line
- A long description
- The release date
- Finished or in progress
- License
- Website
- Version

Also, a quest could have the following optional images:
- quest_logo.png: a 64x32 logo to be displayed as an icon in the quest list. If it does not exist, the Solarus logo will be displayed as a fallback.
- quest_art.png: a bigger image to be displayed in the main area for the selected quest. Size to be decided.
- a few screenshots?

**Comment by oclero** [comment]
For art.png, I can give a template (Gimp and Photoshop) to create a box art like this: http://www.solarus-games.org/wp-content/uploads/2010/01/zsdx_box_front_fr1.jpg.
It would be cool if all Solarus quest had a similar box art like real material games.
I can even make a tutorial "How to create your custom Zelda logo" hahaha ^^

**Comment by christopho** [comment]
art.png could be a box or simply a big banner.

**Comment by christopho** [comment]
Mockup from @oclero: http://i.imgur.com/QSfUBdd.png

**Comment by oclero** [comment]
![sans titre - 2](https://cloud.githubusercontent.com/assets/1050389/12795466/88122646-caba-11e5-8229-6fe90ab20e1e.png)
@christopho  in case of Imgur deletes the file, it's uploaded here now :)

**Comment by christopho** [comment]
Done (the change of quest.dat format, not the full GUI yet)
