### ISSUE TITLE
Crash at initialization: "missing ability"

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#846]
I get a crash at initialization. It says "missing ability", and then it crashes. Nothing appears in error.txt file. It happens sometimes, but not very often (once per 20 or 30 times I run the game). (It must be something of the initialization, but I do not know what.)

**Comment by Diarandor** [comment]
Christopho said that he will give more details in the error messages, so I might be able to find the cause of the bug.

**Comment by christopho** [comment]
For 1.5, at least improve the error message.

**Comment by christopho** [comment]
@Diarandor: with the last snapshot you should now have a better error message. Cam you report it here if you get the crash again?

**Comment by Diarandor** [comment]
Bad (or good?) news: I have not seen the crash lately. Maybe it has been fixed (which is unlikely), or maybe I changed something in my initial scripts lately, which would explain that it stopped happening.

I close the issue. If the crash reappears I will reopen this issue.
