### ISSUE TITLE
Bug: sprite of hero cannot be shifted

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#853]
I am trying to make the custom jump by using a shift on the sprite of the hero to set the height at each instant during the jump, instead of modifying the image file of the sprite. I wrote:
```
hero:get_sprite():set_xy(0, height)
```
But the sprite of the hero does never shift. There is no error in error.txt.
Is this a bug or am I doing something wrong?

**Comment by christopho** [comment]
This must be a bug.

**Comment by christopho** [comment]
Should be solved by the fix of #855. hero:get_sprite() was sometimes returning the wrong sprite if hero:set_tunic_sprite_id() was used.
