### ISSUE TITLE
Request: add callback to sprite:set_animation(animation_name)

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#861]
For the hero entity, the function set_animation has a callback:
``` hero:set_animation(animation, [callback]) ```

Why not adding a callback to the function:
``` sprite:set_animation(animation_name) ```?

**Comment by Diarandor** [comment]
Whoops. I had forgotten that there was already an event:
``` sprite:on_animation_finished(animation) ```
so better to close this issue since it is unnecessary.

**Comment by christopho** [comment]
Actually I agree, I always wanted this. The event will still exist, but a callback is easier to use. It will also be more consistent with functions like game:start_dialog(), sol.timer.start(), movement:start(), etc.

**Comment by Diarandor** [comment]
Ok, thanks!

**Comment by christopho** [comment]
The second parameter could be either a function (the callback) or a string (the name of the animation to set next).
