### ISSUE TITLE
Crash: "Fatal: Invalid keyboard key number: 1073742086"

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#863]
This is the second time I get this crash when starting Solarus (the first one was one or two weeks ago more or less). This is probably a very rare one. The error I got:
[Solarus] [910] Fatal: Invalid keyboard key number: 1073742086

**Comment by Diarandor** [comment]
Maybe I pressed unconsciously some key of the keyboard or the joystick. But I do not know what I did that produced the crash.

**Comment by MetalES** [comment]
It happend to me while I pressed "ù" (249)

**Comment by christopho** [comment]
Should now be fixed, it was due to a refactoring in the development version 1.5. No such crash in 1.4.
