### ISSUE TITLE
Crash when directions of sprite animation are missing

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#864]
If there are missing directions of some sprite animation, Solarus crashes with no error.

**Comment by christopho** [comment]
Which sprite exactly? A hero sprite?

**Comment by Diarandor** [comment]
Yes. If a direction is missing for an animation of the sprite of the hero, it crashes (either at initialization, or when the sprite is needed). The error in error.txt does not always appear (only sometimes, and we get something like "[Solarus] [5490] Fatal: Invalid sprite direction 3: this sprite has 3 direction(s)", but other times there is no error). There should always be an error to notify what is producing the crash.

The crash also happens for the sprites of enemies (and probably other entities), but in that case the error appears (at least in the cases I have checked).
