### ISSUE TITLE
Add function hero:is_walking()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#873]
Add a function "hero:is_walking()" to know if the hero is walking.

Since the animations of the tunic sprite can be changed and even fixed (using the event sprite:on_animation_changed() of the tunic sprite), the function sprite:get_animation() is not always the solution to know if the hero is walking or not.

The function should return true if the hero is being moved either by the player, or by a built-in movement.

Note that this function, combined with hero:get_state(), can be used to distinguish if the hero is walking or stopped when he is in "free" state (something similar was requested by wrightmat here: https://github.com/christopho/solarus/issues/774).

**Comment by christopho** [comment]
After discussion, closing the issue because this can be done easily in Lua:

    local m = hero:get_movement
    return m ~= nil and m.get_speed ~= nil m:get_speed() > 0

**Comment by Morwenn** [comment]
Missing a `and` in the return expression?

**Comment by christopho** [comment]
Indeed, just fixed it. Thanks
