### ISSUE TITLE
Add event on_target_reached for target movements

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#874]
Add an event on_target_reached for target movements.
The event should be called only if the target is reached by the movement.

Edit: this may be useful for the new camera, used as a callback when the camera moves, to make cutscenes.

**Comment by christopho** [comment]
What about using the callback parameter of movement:start()?
And there is also camera:on_movement_finished().

**Comment by Diarandor** [comment]
I did not know that the event target_movement:on_finished() was being called (because actually target movements never end). Then there is no need for this event.

**Comment by christopho** [comment]
Yes. Reaching the target can be seen as the movement finishing, and if the target moves again later, the movement automatically restarts.
