### ISSUE TITLE
Feature request: hero:get_facing_entity()

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#877]
Add the function "hero:get_facing_entity()" (or maybe "hero:get_interaction_entity()") returning the only entity facing the hero which can be interacted by him. If there is no such entity, the function would return nil.

This can be used to notify the HUD script if there is a possible interaction (before interacting), and depending on the entity we could display the correct text or image at the HUD.

**Comment by Diarandor** [comment]
If the hero is facing a wall that can be grabbed, maybe we could return the string "wall", if you agree. Just  to notify the HUD.

**Comment by christopho** [comment]
hero:get_facing_entity() should be doable for 1.5.

**Comment by Diarandor** [comment]
Thanks a lot christopho!!!

This is a great improvement to allow the HUD to know that the hero can interact with custom entities without doing tricky and annoying things with scripts.
