### ISSUE TITLE
Request: Do not create built-in sword when changing hero tunic animation directly

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#882]
If we change the animation of the tunic of the hero, sometimes the built-in sword is created, depending on the animation (for instance, it is created for the "spin attack" and "sword tapping" animations, but not for the "sword" animation).

To create a custom sword, it is really annoying that the built-in sword appears when we change the animation of the tunic of the hero. The built-in sword should not be created in these cases. The same problem might happen for other built-in weapons and associated sprites, but I have not checked this.

(Since the spin attack is going to be removed someday from the engine and replaced by some custom entity, these kind of problems from the built-in part must be solved.)

**Comment by Diarandor** [comment]
As a workaround I will use"sword_tap" instead of "sword_tapping" as the name of the tapping animation, and the same for other animations if needed.

**Comment by Diarandor** [comment]
Should I close this issue?

**Comment by christopho** [comment]
What about never giving the built-in sword ability to the player?

**Comment by Diarandor** [comment]
Yes, you are right, and it worked. Thank you again!
I had completely forgotten about the sword ability functions. Sorry for the annoyance. :S

**Comment by christopho** [comment]
No annoyance. I am glad to see that there is a good solution.
