### ISSUE TITLE
Segfaulting project

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus#885]
I'm in the middle of making my first project. the error is likely mine own, but the engine completely segfaults. This also makes the editor exist using version 1.4.

My guess is that this is the offender: <https://secure.plaimi.net/~alexander/tmp/tunic1.dat>

Try running that on an empty map.

**Comment by alexander-b** [comment]
I thought maybe the problem was a lack of directions. so I added

    { x = 0, y = 0, frame_width = 24, frame_height = 32, origin_x = 12, origin_y = 29 },
    { x = 24, y = 0, frame_width = 24, frame_height = 32, origin_x = 12, origin_y = 29 },
    { x = 72, y = 0, frame_width = 24, frame_height = 32, origin_x = 12, origin_y = 29 },
    { x = 96, y = 0, frame_width = 24, frame_height = 32, origin_x = 12, origin_y = 29 },

To all animations, but it still segfaults.

**Comment by alexander-b** [comment]
Using the sample quest[0], substituting the PNG[1], worked fine. I don't really know why...

[0]  <https://secure.plaimi.net/~alexander/tmp/tunic1.dat.1>
[1]  <https://github.com/christopho/solarus/blob/dev/sample_quest/data/sprites/hero/tunic1.dat>

**Comment by christopho** [comment]
Fixed by https://github.com/christopho/solarus/commit/a38017bbac3f0570949bfcb8c2970f51ceda540b
