### ISSUE TITLE
Change in Lua API "sprite:synchronize(reference_sprite)" by "sprite:synchronize([reference_sprite])"

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#890]
Allow to stop sprites synchronization. We could use the method "sprite:synchronize(reference_sprite)" to do this: if the refefence_sprite is nil, then the synchronization would be stopped:
```Lua
sprite:synchronize(nil)
```

**Comment by Diarandor** [comment]
Whoops, I didn't see in the API that this was already done.
Sorry!

**Comment by Diarandor** [comment]
I overlocked the API because it appears as "sprite:synchronize(reference_sprite)" instead of "sprite:synchronize([reference_sprite])", i.e., the brackets for the optional parameter are missing. It would be nice if that is changed in the Lua API.

**Comment by christopho** [comment]
Fixed
