### ISSUE TITLE
Add ability to hide mouse cursor

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus#891]
For games that use mouse input, it's pretty much necessary to be able to use a custom cursor. I suggest adding sol.input.show_cursor(), sol.input.hide_cursor(), and sol.input.is_cursor_visible(). These would correspond to int SDL_ShowCursor(1), SDL_ShowCursor(0), and SDL_ShowCursor(-1) respectively. See <https://wiki.libsdl.org/SDL_ShowCursor>.

**Comment by christopho** [comment]
sol.input.set_cusor_visible() and sol.input.is_cursor_visible()

**Comment by alexander-b** [comment]
sol.input seems to deal with only input *event*s. sol.video is a better choice, and already has precedent for functionality like this. E.g. sol.video.is_fullscreen() and sol.video.set_fullscreen([fullscreen]).

**Comment by christopho** [comment]
Agreed :)

**Comment by alexander-b** [comment]
Fixed.
