### ISSUE TITLE
Improve  custom_entity:set_size(width, height) to also take x and y

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus#896]
It would be very helpful if I could set bounding boxes as a sub-box inside my sprite, choosing my own origo. My proposal is in light of this to change custom_entity:set_size(width, height) into custom_entity:set_size(width, height, [origin_x], [origin_y]).

**Comment by Diarandor** [comment]
But there is already: custom_entity:set_origin(origin_x, origin_y).

**Comment by alexander-b** [comment]
Hm, yes this should work. Sorry for the noise!
