### ISSUE TITLE
Provide compile options for excluding non-free art

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus#904]
In order to compile and install a completely free Solarus, there should be a way to not install the non-free art at compiletime.

Preferably the non-free art should reside in a separate repository.

A suggestion would be to use a git submodule for the sample_quest, which is initialised when Solarus is being compiled and installed. The installation instructions could then include instructions on how to disable the non-free art, which would neglect the associated steps when compiling and installing the engine.

**Comment by christopho** [comment]
No more non-free art is provided with the engine.
