### ISSUE TITLE
Feature Request: Individual Small Tileset tabs

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus#908]
Individual small tileset tabs would help to keep things neat and tidy. It is also a way to help the developer to quickly find certain pixel art. For example, a tab name trees can hold the tree tileset image. Naming the tabs would be a very nice addition, but simple alphabet letters could work too. (Naming might make tab length issues) "T" for "T"ree would be fine. Also, it can help avoid license issues between GPL Art and CC-BY pixel art. Separate tabs means that the image files can be on different image files, but will allow use on the same map without tileset change. This gives the developer the ability to layer the GPL art on the creative common art without license violations. What the code (functional data) does not apply to things based on beauty (non-functional data = image files or audio, but audio can easily be called with code.).  I have much beautiful GPL pixel art that I cannot use due to this unless I keep one map just GPL license pixel art. This goes for the majority of other licenses as well.

**Comment by christopho** [comment]
This issue should be in https://github.com/christopho/solarus-quest-editor, not in the engine.
