### ISSUE TITLE
Feature Request: Bitmap Font GUI Setup

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus#909]
The ability to select areas on bitmap font image files would increase the speed of the font set up process. A lot of fonts have different spacing and .tff packages can take quite a bit of time to create from bitmap images. A GUI setup that allows letter selecting would be great. Not only does it save time, but may give developers the motivation to make many fonts.

**Comment by christopho** [comment]
This issue should be in https://github.com/christopho/solarus-quest-editor, not in the engine.
