### ISSUE TITLE
Feature Request: Tileset GUI Setup 8x8 Dimension Change

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus#910]
The 8x8 selecting area is great, but some images might need further dimension changes. A grid like option where changes to the 8x8 would save time for developers when putting together tilesets. That way they will not need to make hundreds of adjustments. For example, there could be a checkbox where the developer can click and change the dimension to 1x1, 2x2, 4x4, 4x6, and etc. I think the 8x8 will be fine for default.

Notes: This might require abilities to zoom further and grids would have to go below 8x8.

![4x4](https://cloud.githubusercontent.com/assets/19560764/15658490/e2a20348-2671-11e6-90c1-d50ce7967677.png)

**Comment by christopho** [comment]
What is the "4x4 selecting area"?

**Comment by Zefk** [comment]
I think that yellow box is 4x4. Let me check my grid.

![4x4](https://cloud.githubusercontent.com/assets/19560764/15658490/e2a20348-2671-11e6-90c1-d50ce7967677.png)

**Comment by christopho** [comment]
This issue should be in https://github.com/christopho/solarus-quest-editor, not in the engine.
