### ISSUE TITLE
Bug: Only dashed grids work for tileset editing

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus#913]
The grid seems to work fine everywhere except for where I set up the tileset. Only the dashed grid works.

I am using the solarus-1.5.0-snapshot-20160511-win32.zip version

![dashed only in tileset properties](https://cloud.githubusercontent.com/assets/19560764/15664074/da3c4cd8-26b5-11e6-9cf8-23d4c6e93ba0.png)

**Comment by christopho** [comment]
This issue should be in https://github.com/christopho/solarus-quest-editor, not in the engine.
