### ISSUE TITLE
Bug: Sprite animation preview lag and walking yellow coordinate blocks not moving issues

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus#914]
With the recent 1.5 Solarus version there is a  great lag for a few seconds before the animation previews correctly. Also, I could not move the yellow coordinate blocks with my mouse for the walking animation. I entered it manually with the input options. I had no issues in the last 1.5 version.

**Comment by christopho** [comment]
This issue should be in https://github.com/christopho/solarus-quest-editor, not in the engine.
