### ISSUE TITLE
Feature Request: Maintain tiles manually adjusted positions when copying

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus#915]
As you can see...the manual positions I entered for the tiles were not copied. That is why maintaining the tiles manually adjusted positions when copying would be a good feature.  Request #910 would fix this, but it might still be needed for already made tilesets or just because they adjusted things manually for something.
![maintain position when copying](https://cloud.githubusercontent.com/assets/19560764/15698441/81435a1c-2779-11e6-9897-a42fb0e8f814.png)

**Comment by christopho** [comment]
This issue should be in https://github.com/christopho/solarus-quest-editor, not in the engine.
