### ISSUE TITLE
Feature Request: Audio preview

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus#916]
Being able to preview the audio in Solarus would quicken things.....especially with over 400 sound effects.

**Comment by Renkineko** [comment]
Issue already exists in christopho/solarus-quest-editor#9

Please search before opening issue and open it in the good repository ;)

**Comment by Zefk** [comment]
I actually did search. I put my requests and bug reports in the wrong repo. I will copy and paste them over there.
