### ISSUE TITLE
Fatal: Wrong center position

### ISSUE THREAD

**Issue by wrightmat** [christopho/solarus#922]
I've gotten this error twice now, seemingly randomly. Once was on a transport, and I was able to fix it by moving the destination slightly on the same map. The second time was during a boss bottle and it seems as though nothing caused it.

There should also be more detail to the error so that the cause can be tracked down.

**Comment by Diarandor** [comment]
This could be the same as this issue, which was fixed:
https://github.com/christopho/solarus/issues/897
Since the issue was recent, the last snapshot does not include the fix.
(I think there was another report of this bug, but I cannot remember now where I saw it.)

**Comment by wrightmat** [comment]
Since that fix was general to quadtrees, it may be related. Once a new snapshot is released, I'll give it a try!

**Comment by wrightmat** [comment]
The new snapshot appears to fix it! Thanks Christopho!
