### ISSUE TITLE
Something wrong with alpha blending?

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#931]
I am not an expert on this area, so **I could be completetly wrong**, but I think there is something wrong with the definition of alpha blending you use:
```
"alpha_blending" (default): This drawable object is alpha-blended onto the destination surface.
outRGB = (srcRGB * srcA) + (dstRGB * (1 - srcA))
outA = srcA + (dstA * (1 - srcA))
```
because it is completely different from the definition of the Wikipedia (https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending), which is given by:
```
outA = srcA + (dstA * (1 - srcA))
if outA = 0 then outRGB = 0
else outRGB = (srcRGB * srcA + dstRGB * dstA * (1 - srcA)) / outA
```
Remark: note that your formula to compute outRGB does not even take into account the amount of transparency of the destination surface, which is probably bad.

**Comment by Diarandor** [comment]
Note that if the destination surface is black and transparent "(0,0,0,0)" when we draw over it with alpha blending, then what we draw over it should be drawn unchanged, unless I am wrong. However, with your definition not taking its transparency into account to compute the outRGB, the surface that is drawn over it will be darkened. 

This may be related with what MetalZelda said in the forum:
http://forum.solarus-games.org/index.php/topic,676.msg3523.html#msg3523
I quote what he said:
> I do have to guess that to be better, the day/night tone surface needs to be in "color_modulate" blending ?
>But, strange thing is, if a surface's color is at 0, 0, 0, 0, it is really dark (while it's alpha is at 0), I don't understand much about surface blendings but if someone has any clues I'll gladly take it.

**Comment by christopho** [comment]
I used the definition from SDL: https://wiki.libsdl.org/SDL_BlendMode

**Comment by Diarandor** [comment]
Then I guess it is ok, altough both definitions are not equivalent and are different alpha blendings.
One of the bad or unexpected things of this blending mode is what I have explained before: if you draw something over a black and transparent surface, that will darken the result. But I guess it is ok.

Would SDL2 allow pixel manipulation somehow? It would be very interesting to have those features soon. In any case we can wait for future releases of Solarus to have it, there is no rush.

**Comment by Diarandor** [comment]
Since this is all defined in that SDL2 library it makes no sense to try to change anything, even if the alpha blending is a different one, it does not matter. I close this issue.
