### ISSUE TITLE
Allow to define custom blending modes

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#932]
Allow to define custom blending modes:
A possible syntax would be: 
``drawable:set_blend_mode("custom", function)``
where the second parameter is a function with arguments:
- src_drawable = {r,g,b,a}
- dst_drawable = {r,g,b,a}
- (maybe other parameters like the entities attached to these drawables, if any?)

Remark: this would allow, for instance, to define pixel precise operations, like substraction, etc. And this is exactly what we need to simulate light effects (like torches in the dark, etc). Other use would be, using the drawable metatable combined with this type of blending mode, to allow drawing everything on greyscale (useful to simulate that the time has been stopped, or to make scenes of the memories of the hero, etc). We could also make the blending depend on the time, for strange and more complicated effects. Etc.

**Comment by Diarandor** [comment]
I have not tested the blending functions yet, but maybe it would be necessary to add some function to refresh/redraw all the surfaces when the blending mode is changed, or something like that.

**Comment by christopho** [comment]
Refresh or redraw does not make sense. The screen is redrawn at every frame.

**Comment by Diarandor** [comment]
Ok, you are right, that does not make sense.

**Comment by Diarandor** [comment]
Since this is all defined in that SDL2 library this issue makes no sense, so forget about this issue. Sorry for the annoyance. I close this issue.
