### ISSUE TITLE
Error with create_custom_entity: "Bad field 'width' (integer expected, got nil))"

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#939]
I do not know if I updated correctly to the last snapshot (July-18-2016). Now I am having the following error each time a custom entity is created dynamically from a script and the optional width and height parameters are not given:

blablabla... (15:38:40) Diarandor_PC: bad argument #1 to create_custom_entity (Bad field 'width' (integer expected, got nil))

Do you have the same problem too?

**Comment by christopho** [comment]
This is normal, you forgot do to this: https://github.com/christopho/solarus-quest-editor/issues/169

**Comment by christopho** [comment]
The width and height of custom entities are not optional. It was a bug that the engine accepted without them.

**Comment by Diarandor** [comment]
Then I think that the documentation is wrong, because it says that the width and height are optional for the function map.create_custom_entity.

**Comment by christopho** [comment]
Right! I just fixed the doc, thanks.

**Comment by christopho** [comment]
@Diarandor I also fixed map:create_custom_entity() calls in the sample quest. You need to do the same in your game.

**Comment by Diarandor** [comment]
Ok, I will do that. Thanks!
