### ISSUE TITLE
Solarus GUI System-wide Config

### ISSUE THREAD

**Issue by Nate-Devv** [christopho/solarus#948]
Related to the original use case of #947. Installing a package to the launcher works, but during package installation, the quests get installed to root's config (sudo solarus will show the quests, but not just solarus).  I'm not sure what the alternative location would be on other systems, but ideally the system-wide config could go in `/etc/solarus` on Linux.

**Comment by christopho** [comment]
I could make "solarus -add /path/to/quest" create system-wide settings instead of user settings.
It is doable with QSettings::SystemScope.
And then the launcher GUI would initialize user settings from global ones the first time.

**Comment by Nate-Devv** [comment]
That sounds awesome! Do you know if QSettings::SystemScope fall back to user settings if the user running the command doesn't have privileges to access system settings?

**Comment by Nate-Devv** [comment]
Sweet, this works for general users, at least on Debian. Going to patch the Debian package.

**Comment by christopho** [comment]
So how does it work? I guess it fallbacks to user settings when the user is not root? Are system settings copied to user settings the first time?

**Comment by christopho** [comment]
@Nate-Devv I just committed https://github.com/christopho/solarus/commit/7489a0f2213d1ce6ac27fc7bd1b088304a1456b5 to avoid duplicated the organization and application names. Can you confirm that it still works? Thanks!

**Comment by Nate-Devv** [comment]
Yeah, it still works.  I was trying to do this, but i was using `.` instead of `::`.

**Comment by Nate-Devv** [comment]
@christopho You are right, that is how it works.  The one problem that this approach has is that if you start the engine and then add another quest as root, it won't pick up on it, but I'm not sure how to fix that, or if it even is something to fix.
