### ISSUE TITLE
hero:get_movement() returns nil when swinging sword

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/solarus#950]
-Context-
As i was reweving my test project, the debug HUD script started to generate errors in the "movement speed" 

-The problem-
As the hero swings his sword, the table "movement" seems to totally disappear until the swinging animation finishes, and then it is available again, wheter you charge the spin attack or not.

**Comment by christopho** [comment]
While the hero is swinging his sword, he is not moving so it is normal that there is no movement.
