### ISSUE TITLE
The API of "item:set_amount_savegame_variable()" has things wrong

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#958]
I think there are some things wrong here:
> item:set_amount_savegame_variable()
> 
> Returns the name of the integer savegame value that stores the amount of this item.
> 
> You should call this function at initialization time if you want your item to store an amount (in addition to its possessed variant). This is typically used for items like the bow and the counter of bombs.
> 
> Return value (string): The savegame variable that should store the possessed amount of this item, or nil to make this item have no associated amount.

The first line should be "item:set_amount_savegame_variable(savegame_variable)",
and the line "Returns the name of the integer savegame value that stores the amount of this item."
and the last paragraph have things wrong too.

**Comment by christopho** [comment]
Fixed by https://github.com/christopho/solarus-doc/commits/dev
Note that documentation issues should be reported in the https://github.com/christopho/solarus-doc project.
Thanks!

**Comment by Diarandor** [comment]
Oops, I had forgotten that there was a repo for the documentation.
