### ISSUE TITLE
Fatal: Failed to convert software surface and Very high RAM consumption

### ISSUE THREAD

**Issue by MetalES** [christopho/solarus#962]
Might be related to issue #933 (This time it is "Failed to convert software surface" rather then "Failed to create software surface"), the probability is extremely high

No matter if 2D acceleration is enabled or not

While playing, if you pause the game and switch between menus, the RAM consumption can reach uninimaginable amount (1.8gb in MoS) before it crash

In BoM, you can reproduce the same thing, without being in the menu, just wait in the exterior for the night "light effect" or go to other maps that use the day / night surface

In my project, same thing.

Unpausing didn't dump the memory.
Looks like sprites are never dumped from the memory and got re-created elsewhere in the RAM (selecting an item also make the RAM consumption higher)
You had to restart the game eigher by closing the program or by reseting it to clean the RAM

There are no lags before the crash

Tested with every project, same thing happen

![sans titre 33](https://cloud.githubusercontent.com/assets/4288633/17518339/daecb892-5e47-11e6-86b9-623999eda96c.png)

**Comment by wrightmat** [comment]
I believe it is related to my logged issue - I've actually gotten both the "failed to convert" and "failed to create" fatal error at different times.

**Comment by christopho** [comment]
This one should be fixed. I will make a Windows snapshot so that you guys can confirm and also tell me if it fixes #933 as well.

**Comment by christopho** [comment]
Reopening until the fix is confirmed.

**Comment by MetalES** [comment]
Tested the snapshot:

- Menus:
You can still get crazy amount of RAM (900mb in my project, but this might be related to my modification though), but after that, it is saturated, and the memory is cleared after a little while

For the light effect, it's also stable, and memory is dumped if the map finish

**Comment by christopho** [comment]
By "dump" I hope you mean "cleared" and not a core dump file.
900 MB is probably specific to your quest, especially if you create lots of objects that remain in scope in your scripts.
The important thing on the engine side is that memory is cleared after a while when the Lua GC decides to.
Ok, closing the issues then.

**Comment by wrightmat** [comment]
I agree that this is resolved. I actually left my game running while I was at work all day - over 8 hours later I came back and there had been no crash! Thanks Christopho!

**Comment by christopho** [comment]
Thanks for the report!
