### ISSUE TITLE
libsdl2-image-2.0-0 and libsdl2-ttf-2.0-0 dependencies missing from Ubuntu repo package (Linux Mint 18/Ubuntu 16.04 x64)

### ISSUE THREAD

**Issue by NeonNyan** [christopho/solarus#982]

**Comment by Nate-Devv** [comment]
Noted, I'll look into this when I get the chance.  I assume that you are using the Ubuntu PPA?

**Comment by NeonNyan** [comment]
Yes, I'm using the ppa listed on the Solarus website: ppa:nate-devv/solarus

**Comment by Nate-Devv** [comment]
Looked into it a little bit. If I compile the packages myself, this error doesn't come up, but it does on the PPA packages. Ubuntu compiles them on their machines, which I have no control over.  There also isn't a dependency on anything else special that solarus depends on.

**Comment by christopho** [comment]
This error is strange because libsdl2-image and libsdl2-ttf are already in Ubuntu repositories.

**Comment by Nate-Devv** [comment]
@christopho the error isn't just limited to libsdl2-image and libsdl2-ttf. Really only qt5 stuff is there when the PPA compiles it.

There's no lua/luajit, for example.

**Comment by Nate-Devv** [comment]
@NeonNyan this isn't an issue with solarus, this is an issue with the solarus debian packages. I have a repository [Nate-Devv/solarus-debian-source](https://github.com/Nate-Devv/solarus-debian-source) for such issues.

**Comment by christopho** [comment]
Ok, closing this issue.
